### ISSUE TITLE
Question: is possible to reference layouts from a maven dependency?

### ISSUE THREAD

**Issue by Kerruba** [ultraq/thymeleaf-layout-dialect#100]
Hi,

maybe is a little bit tricky to explain what I'm going after, I'll try to do my best 😄 

I'm trying to create a website that uses reusable templates. Inside of the templates, I'm splitting different part of the page in different files, i.e header, footer, etc.
This website is "plain vanilla": the idea is to use it as a maven dependency and let the customer provide his own header and footer style that are placed "automatically" in the right piece of the template.

Basically, what happens with Wordpress.

So I'm defining a structure like this

@Controllers: defines the base navigation

@templates
Reuse the pages from the parent project or provide new pages that use parents layout:decorator templates. 
If the user provide a different fragment for the header or the footer or other custom things that are named AS the fragments in the parent project, the custom one take the precedence and are use to populate the page

This way I can create 10 different site, defining 10 different navigation and providing 10 different header and footer, without necessarily re-write the entire template and all the fragments

Do you think something like this is possible and if is possible, how should I do that?

**Comment by ultraq** [comment]
You should be able to do something like that using Thymeleaf's view resolvers.

The project for the website being developed can have the usual one pointing to the templates in their resources or web content directory or wherever they like to put their templates, and then configure another view resolver (probably a [ClassLoaderTemplateResolver](http://www.thymeleaf.org/apidocs/thymeleaf/2.1.4.RELEASE/org/thymeleaf/templateresolver/ClassLoaderTemplateResolver.html)) to point to the shared templates in your Maven module.  Then, whenever a shared template tries to resolve "footer", it'll go down the resolvers in the order defined, finding first the website's own footer and using that, or if the website didn't have a footer, then Thymeleaf will go to the next resolver and that will bring up the standard one brought in with the shared templates module.

So I think some kind of playing around with the view resolvers should give you the flexibility you need to be able to create this customizable website template that you're trying to create.

**Comment by Kerruba** [comment]
So, using directly WAR overlay technology from Maven, it seems I'm already able to reach the `@RequestMapping` in the dependency project, but it seems Layout dialect is not correctly interpreted. I mean, thymeleaf specific dialect is read correctly, but the attribute `layout:decorator`is not interpreted, therefore the template is not constructed

**Comment by ultraq** [comment]
If the `layout:*` attributes weren't processed, then the layout dialect mustn't be on the instance of Thymeleaf being used for the page.  Can you confirm that the layout dialect is loaded?  I think it'll show in the server logs the first time you get a page processed by Thymeleaf and you have the Thymeleaf loggers (`org.thymeleaf`) set to INFO.

**Comment by Kerruba** [comment]
So the problem was that the compiled project was packaged as WAR instead of JAR. Switching to jar solved the problem and I was able to read everything from the "parent" project
