### ISSUE TITLE
a mix up bug report

### ISSUE THREAD

**Issue by lmtoo** [ultraq/thymeleaf-layout-dialect#104]
I recently write a big page,this page have navbar and a logou button,so when click the logout button,will alert a dialog:

```xml
<th:block layout:include="/fragments/dialog::dialog('logout','确认')">
    <th:block layout:fragment="dialog-content">确定要注销吗？</th:block>
    <th:block layout:fragment="dialog-buttons">
        <a class="btn btn-primary" th:href="@{/logout}" role="button">确定</a>
    </th:block>
</th:block>
```

there I include a dialog,and custom the confirm button,
but my content page have a delete button too,
so i write a confirm dialog too,

```xml
<th:block layout:include="/fragments/dialog::dialog('delModal','删除')">
  <th:block layout:fragment="dialog-content">确定要删除？</th:block>
  <th:block layout:fragment="dialog-buttoins">
    <button type="submit" class="btn btn-primary">确定</button>
  </th:block>
</th:block>
```

but when i run up my app,the generated page's confirm buttons all is 

```html
<a class="btn btn-primary" role="button" href="/logout">确定</a>
```

this is not i want ,
my expect is logout dialog's button will be 

```html
<a class="btn btn-primary" role="button" href="/logout">确定</a>
```

delete dialog's button will be

```html
<button type="submit" class="btn btn-primary">确定</button>
```

this will confuse me ....

**Comment by ultraq** [comment]
Are you able to also post what the `fragments/dialog :: dialog` template code looks like?

Also, I just noticed that there's a potential spelling mistake in your code, where you're passing a fragment named `"dialog-buttoins"` instead of what I think should be `"dialog-buttons"`.  Is that just an error in your post, or an actual error in your template code?

**Comment by lmtoo** [comment]
I'm sorry,It's my mistake,thank you for the answer.
