### ISSUE TITLE
No groovy please

### ISSUE THREAD

**Issue by jonhkr** [ultraq/thymeleaf-layout-dialect#105]
Groovy is a dependency of 4.5MB.
Do you really need to use it?
Is there anything that can't be done in plain Java?

4.5MB may not seem a lot, but add it with all other dependencies that are **really** required by applications.

**Comment by jonhkr** [comment]
Never mind, managed to exclude it from my build.

**Comment by zhanhb** [comment]
can thymeleaf-layout-dialect run without groovy?

**Comment by ultraq** [comment]
I don't think it can.  I tried starting an example app with the layout dialect [the last time someone asked this](https://github.com/ultraq/thymeleaf-layout-dialect/issues/88#issuecomment-162100500) and kept getting `ClassNotFoundException`s

**Comment by jonhkr** [comment]
No, it wont render the layout without it.

**Comment by jonhkr** [comment]
Seriously, a small lib turned out in a huge lib just because of syntax.

**Comment by ultraq** [comment]
I've written on another issue [my reasons for moving to Groovy](https://github.com/ultraq/thymeleaf-layout-dialect/issues/98#issuecomment-205568813), even giving the person asking a few tips on ways they could fork and create a Java-only version if they wished.  This is a personal project, and so all of my own opinions and decisions are throughout this code, which not everyone will agree with.  I'm pretty adamant of not going back to Java, so you might want to look at other options.

I don't know off the top of my head of alternative Java-only layout libraries for Thymeleaf, so maybe this is a good opportunity for someone to plug that gap?  There are also a tonne of different ways of doing layouts with Thymeleaf, and version 3.0 even introduced another method with the new [Fragment Expressions](https://github.com/thymeleaf/thymeleaf/issues/451) feature.

So you could fork this project and port it from Groovy, roll your own new Java-only layout library, use vanilla Thymeleaf 3.0 to get you most if not all of what you want for doing layouts, or some combination of all of these! 😀  There are likely to be even more ideas that I've missed.

**Comment by zhanhb** [comment]
https://github.com/zhanhb/thymeleaf-layout-dialect

**Comment by ultraq** [comment]
👍

**Comment by zhanhb** [comment]
but only support jdk 8+

**Comment by OrangeDog** [comment]
Groovy 2.x doesn't support JDK 11, causing many Illegal reflective access warnings.
Groovy 3.x (when released) should.
