### ISSUE TITLE
Version 1.3.3 breaks compatibility with Thymeleaf

### ISSUE THREAD

**Issue by opensource21** [ultraq/thymeleaf-layout-dialect#114]
After upgrading from 1.2.9 to 1.3.3 `th:include` from the standard thymeleaf doesn't work as expected. The most bad part on this is that there are no exceptions or warnings. The content is just missing.
See http://stackoverflow.com/questions/37864881/thymeleaf-thinclude-doesnt-work-after-update-to-spring-boot-1-3 for Details.

**Comment by ultraq** [comment]
Odd, looks like something done for processing of the `<title>` element is getting in the way of all the other directives.  That SO post looks like it's enough to create a test from, so I'll get around to doing that and seeing what the problem might be.

**Comment by ultraq** [comment]
Unfortunately, I don't think I'm ever going to get around to looking at this - it's been open for over 2 years and I've been focused on the 2.x branch for Thymeleaf 3.  Sorry I couldn't get around to attempting this.  Closing.
