### ISSUE TITLE
GroupStrategy with thymeleaf 3.0 not working? 

### ISSUE THREAD

**Issue by JeonGyungMin** [ultraq/thymeleaf-layout-dialect#117]
hi. 

thymeleaf 3.0 with thymeleaf-layout-dialect is not working. 

Configuation Code

    @Autowired
    private ApplicationContext applicationContext;

    @Bean
    public GroupingStrategy groupingStrategy() {
        return new GroupingStrategy();
    }
    @Bean
    public SpringResourceTemplateResolver templateResolver() {
        SpringResourceTemplateResolver templateResolver = new SpringResourceTemplateResolver();
        templateResolver.setApplicationContext(applicationContext);
        templateResolver.setPrefix("/templates/");
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode(TemplateMode.HTML);
        templateResolver.setCharacterEncoding("UTF-8");
        templateResolver.setCacheable(false);

        return templateResolver;
    }

    @Bean
    public SpringTemplateEngine templateEngine() {
        SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        templateEngine.setEnableSpringELCompiler(true);
        templateEngine.setTemplateResolver(templateResolver());
        templateEngine.addDialect(new LayoutDialect(groupingStrategy()));
        templateEngine.addDialect(new SpringSecurityDialect());

        return templateEngine;
    }

    @Bean
    public ThymeleafViewResolver thymeleafViewResolver() {
        ThymeleafViewResolver thymeleafViewResolver = new ThymeleafViewResolver();
        thymeleafViewResolver.setTemplateEngine(templateEngine());
        thymeleafViewResolver.setOrder(1);
        thymeleafViewResolver.setCharacterEncoding("UTF-8");
        thymeleafViewResolver.setViewNames(new String[] {"thymeleaf/*"});
        return thymeleafViewResolver;
    }

Error Message. 

` org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'groupingStrategy' defined in com.royalroad.thand.config.ThymeleafConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [nz.net.ultraq.thymeleaf.decorators.strategies.GroupingStrategy]: Factory method 'groupingStrategy' threw exception; nested exception is java.lang.NoClassDefFoundError: org/thymeleaf/dom/Node

How to fix it? any idea?

**Comment by zhanhb** [comment]
thymeleaf-layout-dialect 2.0 not released yet. Current thymeleaf-layout-dialect supports only thymeleaf 2.1.

**Comment by JeonGyungMin** [comment]
thanks for your quick reply
