### ISSUE TITLE
Null pointer in layout:insert/include if no selector (:: element) is specified

### ISSUE THREAD

**Issue by AlexKovalevich** [ultraq/thymeleaf-layout-dialect#120]
When using old style references like: layout:include="/content/header.html" or layout:include="~{/content/header.html}" or layout:insert - then null pointer exception gets thrown. 

This is because fragmentExpression.fragmentSelector in TemplateModelFinder.groovy:74 is null if no selector is specified. If selector is specified like layout:insert="~{/content/header.html :: **html**}" then framework digests this syntax.

I'd suggest, if possible, adding null check for fragmentExpression.fragmentSelector and substitute it with root element by default if such concept exists in Thymeleaf.

`java.lang.NullPointerException: Cannot invoke method execute() on null object
	nz.net.ultraq.thymeleaf.models.TemplateModelFinder.findFragment(TemplateModelFinder.groovy:74) ~[thymeleaf-layout-dialect-2.0.0.jar:na]
	at nz.net.ultraq.thymeleaf.models.TemplateModelFinder$findFragment$1.call(Unknown Source) ~[na:na]
	at nz.net.ultraq.thymeleaf.includes.IncludeProcessor.doProcess(IncludeProcessor.groovy:84) ~[thymeleaf-layout-dialect-2.0.0.jar:na]
	at org.thymeleaf.processor.element.AbstractAttributeModelProcessor.doProcess(AbstractAttributeModelProcessor.java:76) ~[thymeleaf-3.0.0.RELEASE.jar:3.0.0.RELEASE]`

**Comment by ultraq** [comment]
Thanks for the bug report!  I actually don't have any tests around including entire templates for the insert/include/replace processors, so this is a good find.

**Comment by ultraq** [comment]
I've uploaded a `2.0.1-SNAPSHOT` version of the layout dialect with a fix for this in it.  If you could give it a try and let me know if that helps with this issue, that'd be appreciated.

**Comment by AlexKovalevich** [comment]
Sorry I couldn't figure out where to download 2.0.1-SNAPSHOT, so I built it from trunk and so far all looks good.
Thank you for quick turnaround !

**Comment by ultraq** [comment]
You raised the issue and caught me at a good time 😁

If you're using Maven, then the Thymeleaf website has a bit in the FAQ about getting snapshot versions: http://www.thymeleaf.org/faq.html#use-snapshot  (There's no section like that for Gradle, so that might make a good addition to the docs.) Otherwise, recompiling from source like what you've done is a really good option.

Now, on to the other regression bug you've raised! 😀

**Comment by AlexKovalevich** [comment]
Thank you for explaining it, Emanuel! It would take me for a while to figure it out myself :)
For those who is interested the direct URL is: https://oss.sonatype.org/content/repositories/snapshots/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/
