### ISSUE TITLE
Possible Memory Leak 

### ISSUE THREAD

**Issue by tobiasflohre** [ultraq/thymeleaf-layout-dialect#122]
We did some performance tests and stumbled over a memory leak. If you take a look at the following file, you see that there are Thymeleaf objects held by a Groovy map, and there's no other Groovy in our application than the layout dialect.
[Leak Suspects.pdf](https://github.com/ultraq/thymeleaf-layout-dialect/files/359576/Leak.Suspects.pdf)

I've looked into your code and have one assumption: There's that static FragmentMap which is filled for each IContext object, and I don't see any point in your code where you delete entries from that Map. It's just getting bigger and bigger.
Our 4GB heap application doesn't respond anymore after a number of requests that's not very high (like 10000 or less), so it's a very serious thing for us.  

We can provide you with a heap dump, if you want.

**Comment by zhanhb** [comment]
Maybe ChildEventIterator line 70, ChildModelIterator line 68,70, IModelExtensions line 180,203,204 was to blame. These codes will create ExpandoMetaClass instance.

Can you help to test my artifact? I am trying to rewrite the dialect in java. 
com.github.zhanhb:thymeleaf-layout-dialect

**Comment by tobiasflohre** [comment]
@ultraq Hm, when I look into the code of FragmentMap again: you just add the FragmentMap to each IContext, so if the IContext object is garbage collected like it should, there should be no problem. However, the problem exists - tell us if we can help identifying the root cause. There must be some Groovy map holding objects too long.

**Comment by ultraq** [comment]
Thanks for the analysis @tobiasflohre!  I've got a YourKit license lying around here somewhere so it should show me the same things you've discovered once I turn it back on.  I'll keep a look out for those objects you've identified in particular.

**Comment by ultraq** [comment]
Hey @tobiasflohre, that heap dump might be a good idea, although I'm not sure how to transfer something of that size around.  Ideas?

I'm currently trying to generate a lot of load on a test site, so it might be a while before I can see things at the same magnitude as in the PDF you've shared.

**Comment by tobiasflohre** [comment]
You got mail!

**Comment by zhanhb** [comment]
Groovy is slower than java and takes more memory consumption. Add annotation CompileStatic can make that better.

**Comment by tobiasflohre** [comment]
It's Tomcat 7.0.37 and Java 1.7.0_72. Thanks for the efforts.

**Comment by tobiasflohre** [comment]
We've looked into this a little bit further, and we also see that each object is held by one weak and one soft reference. The soft reference is only garbage collected when the JVM is running out of memory, and because there's a weak AND a soft reference to the objects, all objects are only garbage collected when the JVM is running out of memory. We saw that memory consumption is going up through the JVM's lifetime, which is 100% explicable with those soft references. Maybe our JVM was not perfectly configured, that could be one reason why it died in the end (when it should have just thrown away all the soft references), but anyway: Using soft references is wrong IMO. The objects held there are held for one request and not used again, they should be garbage collected as soon as possible.
Maybe you see something in the reference stack of the soft reference that explains to you why it is held (thread-bound meta programming stuff?):
![softreference](https://cloud.githubusercontent.com/assets/1804555/16873589/9181a6a2-4a94-11e6-920e-d7ccd47767d6.gif)

For comparison, here the reference stack of the weak reference of the same object.
![weakreference](https://cloud.githubusercontent.com/assets/1804555/16873606/a5df3506-4a94-11e6-81af-7e34f9d62b97.gif)

**Comment by ultraq** [comment]
*Warning, long and rambly paragraph, mainly for my own benefit if I need to come back to this in future...*

At first I was first going to try removing some closures that *seemed* responsible for the soft/weak references we've seen (our tools always showed layout dialect closures that had any kind of reference to a static as somewhere between the GC root and the large objects in memory), but I did some more digging to try find what code was creating those large objects and found that one of the meta-programming methods I added, `findModel` was being rather wasteful in that it called another meta-method, `find` (returns a Thymeleaf template event and creates a meta-class for every returned object which Groovy then goes and tracks in that gigantic meta-class cache that our tools are identifying as the single instance holding on to so many `OpenElementTag` objects), but it didn't even use the template event; only the index value of the model on the meta-class! (https://github.com/ultraq/thymeleaf-layout-dialect/blob/f18a36d7bc71731e5f0fe8a0f33ad0128bd26166/Source/nz/net/ultraq/thymeleaf/models/extensions/IModelExtensions.groovy#L200)  I thought that was rather wasteful so I created a new method, `findIndexOf`, for returning the index of an event in the model without all of the overhead, changed `findModel` and some other places in the layout dialect to use that (I found 2 other places making the same wasteful choices), re-ran my load tests and saw some promising improvements.

When comparing load tests between 2.0.0 and a 2.0.1-SNAPSHOT with the above changes:
 - the memory impact of `findModel` has been cut by anywhere from 1/2 to 1/10th, depending on the caller and the way it was used
 - the over-time memory profile even allowed for the old generation heap to decrease in size at several points, especially after a forced GC I perform at the end of every test to see only the leaking objects
 - 10 million less objects were created
 - the time spent on GCs was cut in half
 - and it performed 20% less GCs

Here are some telling screenshots:

Before (2.0.0):
![screen shot 2016-07-16 at 6 28 29 pm](https://cloud.githubusercontent.com/assets/1686920/16893155/79ed52da-4b83-11e6-9e85-268fc520d87d.png)

After (2.0.1-SNAPSHOT):
![screen shot 2016-07-16 at 6 28 11 pm](https://cloud.githubusercontent.com/assets/1686920/16893158/8197e7de-4b83-11e6-940c-80d458312815.png)

@tobiasflohre, would you be able to give the 2.0.1-SNAPSHOT version a test and see if it helps with the memory issues you're seeing at all?

**Comment by tobiasflohre** [comment]
I will give it a try Monday morning!

**Comment by tobiasflohre** [comment]
It's much better now, in first tests we couldn't crash the JVM anymore. So whatever you did, it's an improvement, though there's still a lot going on in the heap.
We noticed that the soft references are coming from a ThreadManagedMetaBeanProperty to Model classes:
![2016_07_18_13_05_41_eclipse_memory_analyzer](https://cloud.githubusercontent.com/assets/1804555/16915789/c48623f4-4cf9-11e6-9f8d-e6fc5d17e7b7.jpg)
I took a look at your Extensions classes, and IModelExtension is the only one (together with IAttributeExtensions) that is using additional meta bean properties. We can see large amounts of other model objects in our heap only if they are referenced from a Model-class (for example OpenElementTag). So I'm pretty sure the soft references we see are coming from the usage of additional meta properties.
Interesting that ThreadManagedMetaBeanProperty JavaDoc is talking about weak references while the implementation is using soft references...

**Comment by ultraq** [comment]
Good to hear it improved 👍  The tests I ran were just using the `decorate` processor over a very basic template with a lot of threads and iterations to exaggerate any problems, but for my own sake I'll do the same with the `include`/`insert`/`replace` processors to see if I can make additional improvements there too.

I'll close this issue, but I'll keep on working on memory improvements as part of the general performance issue I created as #102.

And thanks for trying out 2.0.0 of the layout dialect and raising this - I'm really happy with the improvements to the code this discovery has caused! 😃

**Comment by ultraq** [comment]
> Interesting that ThreadManagedMetaBeanProperty JavaDoc is talking about weak references while the implementation is using soft references...

Under the hood of Java, anything goes!

Just an FYI: I completed the `include`/`replace`/`insert` tests and found that `include` was also inefficient and managed to make some improvements there with gains similar to what I did for `decorate` (`insert`/`replace` are still miles better though since Thymeleaf 3 has better built-in support for what they do which I just take advantage of).  This will also be in the `2.0.1` release.

**Comment by cschockaert** [comment]
Just an FYI, we runned into this problem and even if it's a weak + soft reference, our servers constantly crashed after few day.
Here is a memory dump graph  (generated by that interpreter http://dr-brenschede.de/bheapsampler_bin/README.txt) just before the crash.
[memory_graph.pdf](https://github.com/ultraq/thymeleaf-layout-dialect/files/383283/memory_graph.pdf)

it's showing that the memory leak represent 3300 MB (our Xmx is 12G) 
here are our jvm parameters : 
-Xms12G -Xmx12G -Xss256K -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseLargePages -XX:+UseParNewGC -XX:CMSInitiatingOccupancyFraction=85 -XX:PermSize=512M -XX:MaxPermSize=512M -XX:LargePageSizeInBytes=2m -XX:MaxTenuringThreshold=16 -XX:NewRatio=3 -XX:ParallelCMSThreads=3 -XX:ParallelGCThreads=8 -XX:SurvivorRatio=5 -XX:TargetSurvivorRatio=70 -verbose:gc -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=20 -XX:GCLogFileSize=1000K -XX:-UseAdaptiveSizePolicy -XX:+PrintPromotionFailure -XX:+PrintGCApplicationStoppedTime -XX:+PrintTenuringDistribution -XX:PrintFLSStatistics=1

(java build 1.7.0_79-b15)


we don't really run out of memory, but our gc times are increasing a LOT, and the server cannot serve client request correctly so we have to reboot it...

We are updating from 2.0.0-snapshot to  2.0.1, hopping this will be resolved.

**Comment by ultraq** [comment]
> We are updating from 2.0.0-snapshot to 2.0.1, hopping this will be resolved.

I hope 2.0.1 squashes those memory problems too @cschockaert !
