### ISSUE TITLE
Excessive Warn logging info about compatibility 

### ISSUE THREAD

**Issue by AlexKovalevich** [ultraq/thymeleaf-layout-dialect#124]
This is just a minor suggestion about loggin:

When running on old code (thymeleaf 2.x.x + thymeleaf layout dialect 1.x.x) thymeleaf layout dialect 2.0.0 logs lots of repetitive information at warn level like
`WARN  n.n.u.t.fragments.FragmentProcessor - You don't need to put the layout:fragment/data-layout-fragment attribute into the <head> section - the decoration process will automatically copy the <head> section of your content templates into your layout page`

It also logs similar messages if you use **include** instead **insert**.

**Problem:** it clutters log and requires switching log level to error otherwise log file will grow incredibly fast if you have couple of those messages per page view. I'm working of web app which has tons of libraries (hibernate, spring, thymeleaf, elastic search, etc) and none of them generates warn messages repetitively when it's not an error. If it's compatibility issue they would generate warn once during initialization.

I also think having warn level in production makes sense in many cases when it's not a critical error but requires attention.

It keeps generating warning even when thymeleaf cache is enabled.

**Options:**
-I think the most perfect solution would be to figure out what kind of TemplateHandler is currently working, if it's ModelBuilderTemplateHandler then likely its parsing template and it's OK to show any messages as it won't likely to be repeated often, if it's ProcessorTemplateHandler - then template just gets evaluated, and maybe no need to log about it.
-set log level to debug - easy to do. Nobody used debug in production for a long time.
-slf4j does not support dynamic level loggin like logger.log(LogLevelEnum.WARN, "Message") ; so making it configurable would require a helper class
-do nothing and let developers log filter warn level messages from "nz.net.ultraq.thymeleaf"

This is just suggestion to think about.
Thank you!

**Comment by ultraq** [comment]
Thanks for the suggestions @AlexKovalevich 👍

I think I'd like to do like the other libraries do and generate a single warning once during initialization.  The layout dialect doesn't really know what incompatibilities there are until it hits them, so maybe I could set a static flag on the relevant classes to say that the incompatibility has been logged and then never log it again once set.  It's crude and sometimes things might get logged a few times in certain multi-threaded/parallel scenarios, but it'll be performant and it won't be the end of the world if it logs a few times during that window.

Anyway, cutting down on the logging is a good idea and I'd like to do something about it.

**Comment by ultraq** [comment]
Logging of warnings reduced to just the first time the relevant item was encountered.

**Comment by sp193** [comment]
I started using Thymeleaf at 3.x, so I'm not familiar with the syntax of the older versions. I get the warning mentioned above when I have something like this in my layout:
```
<head>
		<th:block layout:fragment="beforeFontAwesome"></th:block>
		<link href="font-awesome/css/fontawesome.min.css" rel="stylesheet" type="text/css" />
</head>
```

And do this in my view, which is decorated with the template above:
```
<html>
	<th:block layout:fragment="beforeFontAwesome"> <!-- Must be declared outside of header to work -->
		<!-- include Formio plugin. Do it before including Font Awesome, as Formio.js 4.13.x includes Font Awesome 4. -->
		<link href="formio.full.min.css" rel="stylesheet" />
		<script src="formio.full.min.js"></script>
	</th:block>
</html>
```

Is it not legal? If so, then how can I achieve the same effect, but with the 3.x syntax? Or at least, could somebody please help explain the meaning of this warning? For some reason, I cannot find any mention of this warning anywhere outside of this page.

I came up with this design to work around a problem I have with using Font Awesome 6.x, with a library that implicitly includes Font Awesome 4.7.0. I'm using this template as a basic template for other templates, which do not all need this workaround - thus the "beforeFontAwesome" fragment may not be defined.

Thanks in advance.

**Comment by ultraq** [comment]
Hey there, so what you're doing is allowed, but it does somewhat conflict with an existing feature of the layout dialect in that it will automatically merge the elements found in `<head>` sections together.  That feature will normally append items in the `<head>` section of the content pages to the `<head>` section of the layout, but can't do 'prepending' of certain elements like you're attempting to do with your example.  You could try provide your own `SortingStrategy` to achieve that as outlined here the docs: https://ultraq.github.io/thymeleaf-layout-dialect/processors/decorate/#head-element-merging

Also, this warning message was created at a time that no `<th:block>` was in Thymeleaf, so devs would often resort to strange workarounds that could result in invalid templates.  I did really want to discourage it back then, but we have some more options now and it's clear that I can't account for all the ways devs will want to transform their `<head>` sections, so it could be time to retire this warning.  I'll raise a new issue for that and ponder it there.
