### ISSUE TITLE
VariableDeclarationMerger performs different behaviors as org.thymeleaf.standard.expression.AssignationUtils

### ISSUE THREAD

**Issue by zhanhb** [ultraq/thymeleaf-layout-dialect#126]
If both the layout and the input have attribute th:with="value='hello, world!'", the merger can raise an IllegalArgumentException

**Comment by zhanhb** [comment]
This issue was moved to zhanhb/thymeleaf-layout-dialect#4

**Comment by ultraq** [comment]
Ah yep, I think I'm doing something like `String.split` on the `,`, which will cause this to be a problem.
