### ISSUE TITLE
Missing ExpressionProcessor

### ISSUE THREAD

**Issue by ochsA** [ultraq/thymeleaf-layout-dialect#128]
With 2.0.1 i got the Exception java.lang.NoClassDefFoundError: nz/net/ultraq/thymeleaf/expressions/ExpressionProcessor
at nz.net.ultraq.thymeleaf.decorators.DecorateProcessor.doProcess(DecorateProcessor.groovy:110)

and the class misses in my distribution.. what's wrong?

**Comment by ddelamotte** [comment]
You forgot to include the additonal JAR for expressions added since 2.0.1

Le 27 juil. 2016 ? 16:49, ochsA <notifications@github.com<mailto:notifications@github.com>> a ?crit :


With 2.0.1 i got the Exception java.lang.NoClassDefFoundError: nz/net/ultraq/thymeleaf/expressions/ExpressionProcessor
at nz.net.ultraq.thymeleaf.decorators.DecorateProcessor.doProcess(DecorateProcessor.groovy:110)

and the class misses in my distribution.. what's wrong?

-

**Comment by ddelamotte** [comment]
Add this to your dependencies
<dependency>
    <groupId>nz.net.ultraq.thymeleaf</groupId>
    <artifactId>thymeleaf-expression-processor</artifactId>
    <version>1.1.1</version>
</dependency>

**Comment by ultraq** [comment]
This dependency is already a part of the layout dialect (see: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/build.gradle#L50, or the generated POM on Maven: https://repo1.maven.org/maven2/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/2.0.1/thymeleaf-layout-dialect-2.0.1.pom) so should be downloaded/installed by your build tools when they're run.

If you opted to download the layout dialect via the ZIP bundle (eg: from the Downloads section of the release page on https://github.com/ultraq/thymeleaf-layout-dialect/releases/tag/2.0.1), then all the dependencies including that one are in the Libraries folder, so make sure they're on the classpath of your project when building/running your app.

**Comment by ultraq** [comment]
If you are in some weird state where that dependency isn't being downloaded (which it sounds like), then doing as @ddelamotte suggested and adding the dependency yourself might be one way to kick your build tools in the guts to download it, but you shouldn't have to do that.  I might suggest performing cleans/refreshes of your build tool's cache(s) to make sure it's getting everything right.

**Comment by ochsA** [comment]
Thanks worked fine!
