### ISSUE TITLE
layout:decorator does not work correclty over multiple layers anymore

### ISSUE THREAD

**Issue by Stummi** [ultraq/thymeleaf-layout-dialect#130]
while upgrading thymeleaf to 3 and thymeleaf-layout-dialect within a spring boot application, I noticed that templates behaves differently with multiple decorator layers. The merging logic also behaves different between 2.0.0 and 2.0.1, but both does not resemble the behavior from 1.4, which I think is a bug.

Heres a simple test case with 3 layout files:
layout1.html:
```html
<!DOCTYPE HTML>
<html>
<head>
  <script src="layout1.js"></script>
</head>
</html>
```

layout2.html:
```html
<!DOCTYPE HTML>
<html layout:decorator="layout1">
<head>
  <script src="layout2.js"></script>
</head>
</html>
```

test.html:
```html

<!DOCTYPE HTML>
<html layout:decorator="layout2">
<head>
  <script src="test.js"></script>
</head>
</html>
```

The result with different combinations of thymeleaf and thymeleaf-layout-dialect versions:

Thymeleaf 2.1.5, Dialect 1.4.0
```html
<!DOCTYPE HTML>

<html>
<head>
	
<script src="layout1.js"></script>
	<script src="layout2.js"></script>
	<script src="test.js"></script>
</head>
</html>
```

Thymeleaf 3.0.0, Dialect 2.0.0
```html
<!DOCTYPE HTML>
<html>
<head>

<script src="layout2.js"></script>
<script src="test.js"></script>
</head>
</html>
```

Thymeleaf 3.0.0, Dialect 2.0.1
```html
<!DOCTYPE HTML>
<html>
<head>

<script src="layout1.js"></script>
<script src="test.js"></script>
</head>
</html>
```

The behavior also affects the merging of the body part, I just used the head with single script tags for simplicity of the test case.

**Comment by ultraq** [comment]
Yeah, that definitely looks wrong.  Thanks for the bug report, and the test case PR you've just submitted 😃 

Can you describe in what way the body merging is also incorrect?

**Comment by Stummi** [comment]
Ah, nevermind the body part. While trying to build another test case it turned out to be a usage error on my site. Sorry for the confusion

**Comment by ultraq** [comment]
Hi @Stummi, I've got a fix for the test case you modified and uploaded a `2.0.2-SNAPSHOT` version of the layout dialect to Maven.  Could you give it a try to see if it works for you?

Also, because this fixed the merging of the `<head>` section, I had to make a further fix to how titles were handled in multi-level layouts (now that they were being correctly included) so that it continued to work with the existing test suite.  If you also encounter some title issues, could you let me know?

**Comment by Stummi** [comment]
Hello,

just tried the new version of the artifact and both, merging of script tags and the title handling works as expected for me. Thanks for the update.

**Comment by ultraq** [comment]
Good to hear! 👍  At the moment it looks like I'll get around to creating a proper 2.0.2 release this weekend, which includes this fix.
