### ISSUE TITLE
Localized title in decorator not picked up by title-pattern

### ISSUE THREAD

**Issue by billyboingo** [ultraq/thymeleaf-layout-dialect#136]
Thymeleaf: 3.0.1.RELEASE
Dialect: 2.0.3

I have the following in my decorator:

```
<head>
  <title layout:title-pattern="$CONTENT_TITLE | $DECORATOR_TITLE" th:utext="#{head.title}">Layout</title>
</head>
```
and the follwing in my content page:
```
<head>
  <title th:utext="#{nav.home}">Home</title>
</head>
```

But, for instance, instead of getting the following for Spanish:
`<title>Casa | Mi Lugar</title>`

I get this:
`<title>Home | Layout</title>`

It would seem that the pattern is processed before the th:utext is parsed...

**Comment by billyboingo** [comment]
As a followup:

If I use th:text instead, it works fine.  Interesting.

**Comment by ultraq** [comment]
Ah, I don't look for uses of `th:utext` in dynamic title creation, just `th:text`.  Looks like that's a gap that needs to be filled!

**Comment by ultraq** [comment]
Hi @billyboingo, I've uploaded a `2.0.4-SNAPSHOT` version to the Maven snapshots repository which contains a fix to include `th:utext`/`data-th-utext` when looking for titles to use in the title pattern.  Could you give that version a test to see if it works for you?

**Comment by billyboingo** [comment]
Hi @ultraq.  Thanks for the quick response.  
From my initial testing, this seems to have done the trick.  Thanks!
