### ISSUE TITLE
Model level issue in the <head> section with certain script combinations

### ISSUE THREAD

**Issue by ultraq** [ultraq/thymeleaf-layout-dialect#138]
From this post in the Thymeleaf forums: http://forum.thymeleaf.org/Cannot-set-containing-close-tag-to-skip-when-model-level-is-zero-td4029994.html

Looks like another model level problem, but this time coming out of the processing Thymeleaf is doing with all the handlebars scripts as per Marc's comments.

The last model level bug (#129) was fixed by using a tag processor instead of a model processor (Thymeleaf isn't as strict on modifications to the model when using a tag processor), but I won't be able to do that here.

**Comment by jeongjaejin** [comment]
https://github.com/jeongjaejin/spring-boot-sample-web-thymeleaf3

spring-boot-sample-web-thymeleaf3 is spring boot's reference sample project. (modified slightly.)

Is this the same issue?

Please give me advice on how to solve this problem.

**Comment by ultraq** [comment]
Looks a bit different (this issue is for the `<head>` section), but I'll see if that project might have surfaced something else.

**Comment by ultraq** [comment]
Heya @jeongjaejin, I've taken a look at your sample project and I found that attoparser (the underlying HTML parsing library for Thymeleaf) has configured `<col>` elements to automatically close the parent `<colgroup>`, which then throws the whole "model level" thing off because it means there are additional closing tags where there shouldn't be!  I brought it up with Daniel and he also agrees that it's a bug.

I've raised an issue against attoparser, so you can track/watch that to see how the fix for the `<colgroup>` problem is coming along: https://github.com/attoparser/attoparser/issues/15

**Comment by jeongjaejin** [comment]
Good! Thank you for your efforts.

**Comment by ultraq** [comment]
Haven't heard anything more from the person in the forum, but given what I've seen here and other issues, I implemented a *possible* fix for model level problems to take into account "synthetic" closing tags (tags that don't appear in the original template but that attoparser inserts into the model to balance things out) and not have it affect the model level.

While this now makes the layout dialect less strict when it comes to the HTML spec and all its nuances, this puts it more in line with how Thymeleaf handles these too.
