### ISSUE TITLE
Support multiline fragment expressions

### ISSUE THREAD

**Issue by istonikula** [ultraq/thymeleaf-layout-dialect#140]
Cases 1-7 below work, case 8 does not, i.e. when calling fragments that have parameters:

1. standard legacy syntax: OK
2. standard legacy syntax multiline: OK
3. standard new syntax: OK
4. standard new syntax multiline: OK
5. layout legacy syntax: OK
6. layout legacy syntax multiline: OK
7. layout new syntax: OK
8. layout new syntax multiline: NOT OK

Fragments

>     <th:block th:fragment="hello(foo, bar)">
>         <p th:text="|Hello ${foo} ${bar}|"></p>
>     </th:block>
> 
>     <th:block layout:fragment="hello_layout(foo, bar)">
>         <p th:text="|Hello ${foo} ${bar}|"></p>
>     </th:block>
> 

Cases:

  

>     <th:block th:insert="fragments::hello('case', 1)"></th:block>
>     <th:block th:insert="fragments::hello(
>         'case',
>         2)
>         " />
>     <th:block th:insert="~{fragments::hello('case', 3)}"></th:block>
>     <th:block th:insert="~{fragments::hello(
>         'case',
>         4)
>         }" />
> 
>     <th:block layout:insert="fragments::hello_layout('case', 5)" />
>     <th:block layout:insert="fragments::hello_layout(
>         'case',
>         6)
>         " />
> 
>     <th:block layout:insert="~{fragments::hello_layout('case', 7)}" />
>     <th:block layout:insert="~{fragments::hello_layout(
>         'case',
>         8)
>         }" />
> 

Stack: http://pastebin.com/7KRhW6hZ

**Comment by ultraq** [comment]
Thanks for the bug report!  I think I might already know what might be causing this one.  Will give it a look, hopefully it'll be a quick fix.

**Comment by ultraq** [comment]
I've just uploaded a 2.0.5-SNAPSHOT version of the layout dialect to Maven with a fix for this issue.  Would you be able to try it out @istonikula, see if it works for you?

**Comment by istonikula** [comment]
Yes, with 2.0.5-SNAPSHOT also the case 8 works. Thanks for the quick fix.

**Comment by ultraq** [comment]
👍  Awesome, I'll release the 2.0.5 version soon, there's 1 more bug fix I want to try get into it.
