### ISSUE TITLE
Simplify model level counting algorithm

### ISSUE THREAD

**Issue by ultraq** [ultraq/thymeleaf-layout-dialect#142]
I've recently learned that my understanding of attoparser and all of its various flags and tags (synthetics, unmatched, standalones, etc) is way more complicated than it should be, and it kind of shows in the current implementation of the model level counting algorithm here: https://github.com/ultraq/thymeleaf-layout-dialect/blob/eacdc772ae95c0d680f4bade710a76abee9eb44e/Source/nz/net/ultraq/thymeleaf/models/extensions/IModelExtensions.groovy#L426-L446

I've had some back-and-forth w/ @danielfernandez, and he's pointed out that I really only need to cater for 2 situations:

> In fact, all of that is already done at attoparser/thymeleaf for you, you only have to look at the `isSynthetic()` (for open and close tags) and `isUnmatched()` (for close tags) flags in the tag event objects.
> 
> It’s simple:
> 
> * An open or close tag is **synthetic** when it had to be generated by the parser as a result of tag balancing. It doesn’t appear in the original template, and it shouldn’t appear in the result. But it’s there to correctly balance the markup in memory, and it **does have an influence in model levels** (i.e. hierarchy). Note that Thymeleaf makes AttoParser work in auto-close mode, but not auto-open, so right now you shouldn't find any auto-open tags in Thymeleaf templates --- this said, in the future parsers might be pluggable and people might start applying AttoParser parsers in auto-open mode.
> 
> * A close tag is **unmatched** when it doesn’t correspond to any currently open element. Unmatched close tags do appear in the original template, of course, and they should also appear in the result. But they have **absolutely no influence in the model levels**, most times they are treated as if they were mere text.

With that, I should then be able to simplify the code to something like this:

```groovy
if (IOpenElementTag) {
  modelLevel++
}
else if (ICloseElementTag) {
  if (unmatched) {
    // Do nothing
  }
  else {
    modelLevel--
  }
}
```

This means I don't need to care about synthetic tags or void/standalone tags (I'm guessing they're already covered as "matched" closing tags) or anything else that was cluttering my mind with regards to how attoparser works.

**Comment by danielfernandez** [comment]
> or void/standalone tags (I'm guessing they're already covered as "matched" closing tags).

There are three possible scenarios for void/standalone tags:

`<input>` : 1. Standalone tag (`minimized:false`)
`<input/>`: 1. Standalone tag (`minimized:true`)
`<input></input>`: 1. Standalone tag (`minimized:false`), 2. Unmatched close tag.

So you are right, in your code you should not care about these.

**Comment by ultraq** [comment]
Updated algorithm: https://github.com/ultraq/thymeleaf-layout-dialect/blob/ae291d368a750d45aac1de8e0752e8a2af8f565a/Source/nz/net/ultraq/thymeleaf/models/extensions/IModelExtensions.groovy#L424-L438
