### ISSUE TITLE
Layout ignored on Windows 7 Enterprise

### ISSUE THREAD

**Issue by hellocomrade** [ultraq/thymeleaf-layout-dialect#148]
Hi,

I got a weird issue with layout dialect. The same code works perfectly on my Linux VM, but not on Windows 7 with STS 3.8.3 and Spring Boot 2.0.

Here is pom.xml

```xml
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.BUILD-SNAPSHOT</version>
		<relativePath/> <!-- lookup parent from repository -->
</parent>
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

Here is the TRACE log on Windows 7:
```java
2017-01-12 10:50:25.985 TRACE 10924 --- [nio-8888-exec-1] o.t.t.TemplatePreprocessingReader        : [THYMELEAF][TEMPLATEPREPROCESSINGREADER][http-nio-8888-exec-1] CALLING read(char[], 0, 8192)
2017-01-12 10:50:25.985 TRACE 10924 --- [nio-8888-exec-1] o.t.t.TemplatePreprocessingReader        : [THYMELEAF][TEMPLATEPREPROCESSINGREADER][http-nio-8888-exec-1] READ FROM SOURCE -1 A read operation was executed on the source reader (max chars requested: 9216).
2017-01-12 10:50:25.985 TRACE 10924 --- [nio-8888-exec-1] o.t.t.TemplatePreprocessingReader        : [THYMELEAF][TEMPLATEPREPROCESSINGREADER][http-nio-8888-exec-1] RETURN -1 After trying to read from input: No input left, no buffer left.
2017-01-12 10:50:25.986 TRACE 10924 --- [nio-8888-exec-1] org.thymeleaf.TemplateRepository         : [THYMELEAF][http-nio-8888-exec-1] Finished parsing of template "index"
2017-01-12 10:50:25.987 DEBUG 10924 --- [nio-8888-exec-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8888-exec-1] Starting process on template "index" using mode "HTML5"
2017-01-12 10:50:25.987 DEBUG 10924 --- [nio-8888-exec-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8888-exec-1] Finished process on template "index" using mode "HTML5"
2017-01-12 10:50:25.990 DEBUG 10924 --- [nio-8888-exec-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8888-exec-1] FINISHED PROCESS AND OUTPUT OF TEMPLATE "index" WITH LOCALE en_US
2017-01-12 10:50:25.990 DEBUG 10924 --- [nio-8888-exec-1] org.thymeleaf.TemplateEngine.TIMER       : [THYMELEAF][http-nio-8888-exec-1][index][en_US][12875109][13] TEMPLATE "index" WITH LOCALE en_US PROCESSED IN 12875109 nanoseconds (approx. 13ms)
```

On Linux, the same TRACE and you can tell layout is evaluated:
```java
2017-01-12 15:38:00.414 TRACE 25087 --- [nio-8888-exec-1] o.t.t.TemplatePreprocessingReader        : [THYMELEAF][TEMPLATEPREPROCESSINGREADER][http-nio-8888-exec-1] CALLING read(char[], 0, 8192)
2017-01-12 15:38:00.414 TRACE 25087 --- [nio-8888-exec-1] o.t.t.TemplatePreprocessingReader        : [THYMELEAF][TEMPLATEPREPROCESSINGREADER][http-nio-8888-exec-1] READ FROM SOURCE -1 A read operation was executed on the source reader (max chars requested: 9216).
2017-01-12 15:38:00.414 TRACE 25087 --- [nio-8888-exec-1] o.t.t.TemplatePreprocessingReader        : [THYMELEAF][TEMPLATEPREPROCESSINGREADER][http-nio-8888-exec-1] RETURN -1 After trying to read from input: No input left, no buffer left.
2017-01-12 15:38:00.414 TRACE 25087 --- [nio-8888-exec-1] org.thymeleaf.TemplateRepository         : [THYMELEAF][http-nio-8888-exec-1] Finished parsing of template "index"
2017-01-12 15:38:00.416 DEBUG 25087 --- [nio-8888-exec-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8888-exec-1] Starting process on template "index" using mode "HTML5"
2017-01-12 15:38:00.446 TRACE 25087 --- [nio-8888-exec-1] o.t.T.cache.EXPRESSION_CACHE             : [THYMELEAF][http-nio-8888-exec-1][EXPRESSION_CACHE][CACHE_MISS] Cache miss in cache "EXPRESSION_CACHE" for key "{fragment_selection}layouts/layout".
2017-01-12 15:38:00.447 TRACE 25087 --- [nio-8888-exec-1] o.t.T.cache.EXPRESSION_CACHE             : [THYMELEAF][http-nio-8888-exec-1][EXPRESSION_CACHE][CACHE_ADD][9] Adding cache entry in cache "EXPRESSION_CACHE" for key "{fragment_selection}layouts/layout". New size is 9.
2017-01-12 15:38:00.447 TRACE 25087 --- [nio-8888-exec-1] o.t.s.expression.TextLiteralExpression   : [THYMELEAF][http-nio-8888-exec-1] Evaluating text literal: "'layouts/layout'"
2017-01-12 15:38:00.451 TRACE 25087 --- [nio-8888-exec-1] o.t.TemplateEngine.cache.TEMPLATE_CACHE  : [THYMELEAF][http-nio-8888-exec-1][TEMPLATE_CACHE][CACHE_MISS] Cache miss in cache "TEMPLATE_CACHE" for key "layouts/layout".
2017-01-12 15:38:00.452 TRACE 25087 --- [nio-8888-exec-1] org.thymeleaf.TemplateRepository         : [THYMELEAF][http-nio-8888-exec-1] Trying to resolve template "layouts/layout" as resource "classpath:/templates/layouts/layout.html" with resource resolver "SPRING-RESOURCE"
2017-01-12 15:38:00.452 DEBUG 25087 --- [nio-8888-exec-1] org.thymeleaf.TemplateRepository         : [THYMELEAF][http-nio-8888-exec-1] Template "layouts/layout" was correctly resolved as resource "classpath:/templates/layouts/layout.html" in mode HTML5 with resource resolver "SPRING-RESOURCE"
2017-01-12 15:38:00.452 TRACE 25087 --- [nio-8888-exec-1] org.thymeleaf.TemplateRepository         : [THYMELEAF][http-nio-8888-exec-1] Starting parsing of template "layouts/layout"
```

I have been out of my resort and hopefully, you could shed some light on this.

Many thanks!

**Comment by ultraq** [comment]
Weird, in that I've never had an OS-specific issue before!  The only thing that comes to mind is that template resolution isn't working in a cross-platform manner, like the difference between paths (`/` vs `\` or `\\`, and `:` vs `;`).  From the trace I noticed that you're using classpath resolution which could potentially run into the issues I mentioned, but I would have thought that Java would smooth those all out.

Are you able to give me your prefix and suffix properties if you have any?  Otherwise, I assume they're the Spring Boot defaults?  Also, I notice you're using Spring Boot 2.0.0-SNAPSHOT.  Are you able to make your project work with the latest Spring Boot stable version?

If none of those help, are you able to provide a sample template that exhibits this issue?  (I normally fix these things by first creating a test that breaks, although Travis CI runs Unix environments, so that might not help much for CI...)

Lastly, can you confirm the Thymeleaf and layout dialect versions you're using?  I think it's Thymeleaf 2.x and layout dialect 1.x given your stack trace (Thymeleaf 3 doesn't really have an "HTML5" mode any more).

**Comment by hellocomrade** [comment]
@ultraq 

Thank you for the timely reply!

I tried your suggestion of flipping the slash and no luck on that.

As for the prefix and suffix, I keep Spring Boot default.

Regarding Thymeleaf and layout dialect version, I use Spring Boot 2.0 default as well
```xml
                <thymeleaf.version>2.1.5.RELEASE</thymeleaf.version>
		<thymeleaf-extras-springsecurity4.version>2.1.3.RELEASE</thymeleaf-extras-springsecurity4.version>
		<thymeleaf-extras-conditionalcomments.version>2.1.2.RELEASE</thymeleaf-extras-conditionalcomments.version>
		<thymeleaf-layout-dialect.version>1.4.0</thymeleaf-layout-dialect.version>
		<thymeleaf-extras-data-attribute.version>1.3</thymeleaf-extras-data-attribute.version>
		<thymeleaf-extras-java8time.version>2.1.0.RELEASE</thymeleaf-extras-java8time.version>
```

I actually was able to get layout dialect work today on my colleague's Windows 7. We should have the same core image. The only difference I can tell is that: he's on an older version of STS.

I can put something together on my Github later today and let you know.

Thanks a lot!

**Comment by hellocomrade** [comment]
@ultraq 

Sorry for the delay. I have put a repo at: https://github.com/hellocomrade/thymeleaf-layout-issue-4-ultraq
to demonstrate the issue.

If I go: http://localhost:8080, the index page will have the following at the top

```html
<html xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" layout:decorator="layouts/layout">
```

Which indicates the layout is not recognized.

Again, any suggestion will be highly appreciated!

**Comment by ultraq** [comment]
Darnit, I can't seem to reproduce the problem 😢  The only Windows environment I have is a Windows 10 one and I've cloned your project and it seems to work there.

All I can think of now is to maybe add some additional logging to a new version to try trace what's happening, but since you've got it all there are you able to debug the Spring Boot project and put a breakpoint inside the `DecoratorProcessor`'s `processAttribute` method?  Given the trace in your original post, it's like the decorator processor wasn't even executed, or if it did then either something happened to cause it to exit (the only exit condition I can think of is the exception thrown here: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master-thymeleaf-2.1/Source/nz/net/ultraq/thymeleaf/decorators/DecoratorProcessor.groovy#L80), or the layout template was somehow empty!

Can you verify that the method above is actually being run?

**Comment by hellocomrade** [comment]
Hi @ultraq 

Wish you have had a good weekend break!

Thank you for the tip! I was trying to follow this trace and found out that layout dialect may not be loaded by Thymeleaf Engine at all during initalization. On the Windows 7 with issues, the following log entries are missing
```java
[THYMELEAF] * Dialect [2 of 2]: nz.net.ultraq.thymeleaf.LayoutDialect
[THYMELEAF]     * Prefix: "layout"
[THYMELEAF]     * Processors matching nodes by element attribute [precedence]:
[THYMELEAF]         * "data-layout-decorator" [0]: nz.net.ultraq.thymeleaf.decorators.DecoratorProcessor
[THYMELEAF]         * "data-layout-fragment" [1]: nz.net.ultraq.thymeleaf.fragments.FragmentProcessor
[THYMELEAF]         * "data-layout-include" [0]: nz.net.ultraq.thymeleaf.includes.IncludeProcessor
[THYMELEAF]         * "data-layout-replace" [0]: nz.net.ultraq.thymeleaf.includes.ReplaceProcessor
[THYMELEAF]         * "data-layout-title-pattern" [1]: nz.net.ultraq.thymeleaf.decorators.TitlePatternProcessor
[THYMELEAF]         * "layout:decorator" [0]: nz.net.ultraq.thymeleaf.decorators.DecoratorProcessor
[THYMELEAF]         * "layout:fragment" [1]: nz.net.ultraq.thymeleaf.fragments.FragmentProcessor
[THYMELEAF]         * "layout:include" [0]: nz.net.ultraq.thymeleaf.includes.IncludeProcessor
[THYMELEAF]         * "layout:replace" [0]: nz.net.ultraq.thymeleaf.includes.ReplaceProcessor
[THYMELEAF]         * "layout:title-pattern" [1]: nz.net.ultraq.thymeleaf.decorators.TitlePatternProcessor
```
, which indicates layout dialect is not recognized by Thymeleaf somehow. 

It's actually tracked back to ThymeleafAutoConfiguration in Spring Boot.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/thymeleaf/ThymeleafAutoConfiguration.java#L192

this.dialects is null from dependency resolver. Layout dialect is not loaded at the first place!

Any clue?

**Comment by ultraq** [comment]
I've not used Spring Boot a whole lot, but looking at that auto configuration for Thymeleaf, it looks like dialects are loaded if the class this `@ConditionalOnClass` specifies is present on the classpath.  If that's the case, then what we're trying to figure out here might be a classpath or a dependency/jar problem in that the layout dialect jar might not be present on the classpath of the project when you're running it.

Those should probably be the next things to check.  If you can find out the command that executes your project, see if it specifies a classpath that contains the layout dialect jar.  If you can't get that (eg: because it's your IDE doing the executing), check that the layout dialect is included in the list of jars/libraries for whatever the execution configuration is.

**Comment by hellocomrade** [comment]
@ultraq 

Sorry for the late reply! I'd like to believe I didn't have thymeleaf-layout-dialect.jar on the class path. However, when I revisit this issue today, it appears layout dialect doesn't work on my Linux machine either. Of course, as you know, I am on Spring Boot 2.0.0 SNAPSHOT. Since it's upgraded to Spring Framework 5.0, spring-boot-starter-thymeleaf is now only coming with
```xml
<dependency>
			<groupId>org.thymeleaf</groupId>
			<artifactId>thymeleaf-spring5</artifactId>
</dependency>
```
So, I have to do the following in my own pom.xml to include layout-dialect
```xml
<dependency>
		<groupId>nz.net.ultraq.thymeleaf</groupId>
		<artifactId>thymeleaf-layout-dialect</artifactId>
                <version>2.1.2</version>
</dependency>
```

I am sure thymeleaf-layout-dialect 2.1.2 is on class path, but still doesn't get it work on both Linux and Windows now.

Any clue?

**Comment by hellocomrade** [comment]
```java
[THYMELEAF] TEMPLATE ENGINE CONFIGURATION:
[THYMELEAF] * Thymeleaf version: 3.0.3.RELEASE (built 2017-01-05T00:16:02+0000)
[THYMELEAF] * Cache Manager implementation: org.thymeleaf.cache.StandardCacheManager
[THYMELEAF] * Template resolvers:
[THYMELEAF]     * org.thymeleaf.spring5.templateresolver.SpringResourceTemplateResolver
[THYMELEAF] * Message resolvers:
[THYMELEAF]     * org.thymeleaf.spring5.messageresolver.SpringMessageResolver
[THYMELEAF] * Link builders:
[THYMELEAF]     * org.thymeleaf.linkbuilder.StandardLinkBuilder
[THYMELEAF] * Dialect: SpringStandard (org.thymeleaf.spring5.dialect.SpringStandardDialect)
```

**Comment by ultraq** [comment]
Darnit, I was hoping that your lack of reply meant you figured it out and had it fixed!  Unfortunately I don't know why Spring Boot 2 on your machines (but not your co-workers) isn't working 😕 

I might try get a small Spring Boot 2 project working this weekend so I can try it out myself, see if it refuses to load the layout dialect or something like that.

Here's a thought that just entered my head: since Spring Boot 2 no longer bundles the layout dialect by default, then maybe it removed all the auto-configuration stuff too?  So, have you configured Thymeleaf to add the layout dialect manually, much like how you'd add other non-bundled dialects manually?

**Comment by hellocomrade** [comment]
@ultraq thank you for the reply! Well, if I figured it out, I will definitely post it here in case others may have the same issue.

thymeleaf-layout-dialect 2.1.2 seems to have a compatibility issue with thymeleaf-extras-springsecurity4?
If I put layout dialect in pom.xml, I get: **Could not initialize class org.thymeleaf.extras.springsecurity4.auth.SpringVersionSpecificUtils**

thymeleaf-extras-springsecurity4 has support on Spring 5:
https://github.com/thymeleaf/thymeleaf-extras-springsecurity/blob/7e2847bfe950172d2b733b5dae5e2572b32a5828/thymeleaf-extras-springsecurity4/src/main/java/org/thymeleaf/extras/springsecurity4/auth/SpringVersionSpecificUtils.java

**Comment by hellocomrade** [comment]
@ultraq you are right: it appears Thymeleaf layout dialect was not auto configured anymore in Spring Boot 2.0 Snapshot somehow

In a simpler setup, I have the following configuration that seems to make layout dialect working. Still need some verification though. Codes are from: http://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html

```java
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.thymeleaf.extras.springsecurity4.dialect.SpringSecurityDialect;
import org.thymeleaf.spring5.SpringTemplateEngine;
import org.thymeleaf.spring5.templateresolver.SpringResourceTemplateResolver;
import org.thymeleaf.templatemode.TemplateMode;

import nz.net.ultraq.thymeleaf.LayoutDialect;

@Configuration
public class WebMvcConfig extends WebMvcConfigurerAdapter{
	@Bean
	public SpringResourceTemplateResolver templateResolver(){
	    // SpringResourceTemplateResolver automatically integrates with Spring's own
	    // resource resolution infrastructure, which is highly recommended.
	    SpringResourceTemplateResolver templateResolver = new SpringResourceTemplateResolver();
	    //templateResolver.setApplicationContext(this.applicationContext);
	    
	    templateResolver.setPrefix("classpath:/templates/");
	    templateResolver.setSuffix(".html");
	    // HTML is the default value, added here for the sake of clarity.
	    templateResolver.setTemplateMode(TemplateMode.HTML);
	    // Template cache is true by default. Set to false if you want
	    // templates to be automatically updated when modified.
	    templateResolver.setCacheable(true);
	    return templateResolver;
	}

	@Bean
	public SpringTemplateEngine templateEngine(){
	    // SpringTemplateEngine automatically applies SpringStandardDialect and
	    // enables Spring's own MessageSource message resolution mechanisms.
	    SpringTemplateEngine templateEngine = new SpringTemplateEngine();
	    templateEngine.setTemplateResolver(templateResolver());
	    templateEngine.addDialect(new SpringSecurityDialect());
	    templateEngine.addDialect(new LayoutDialect());
	    // Enabling the SpringEL compiler with Spring 4.2.4 or newer can
	    // speed up execution in most scenarios, but might be incompatible
	    // with specific cases when expressions in one template are reused
	    // across different data types, so this flag is "false" by default
	    // for safer backwards compatibility.
	    templateEngine.setEnableSpringELCompiler(true);
	    return templateEngine;
	}
}

```

**Comment by ultraq** [comment]
> thymeleaf-layout-dialect 2.1.2 seems to have a compatibility issue with thymeleaf-extras-springsecurity4?
> If I put layout dialect in pom.xml, I get: **Could not initialize class org.thymeleaf.extras.springsecurity4.auth.SpringVersionSpecificUtils**
> 
> thymeleaf-extras-springsecurity4 has support on Spring 5:
https://github.com/thymeleaf/thymeleaf-extras-springsecurity/blob/7e2847bfe950172d2b733b5dae5e2572b32a5828/thymeleaf-extras-springsecurity4/src/main/java/org/thymeleaf/extras/springsecurity4/auth/SpringVersionSpecificUtils.java

Weird that these 2 interact like this when they should be completely separate.  Care to raise another issue for that one?

**Comment by hellocomrade** [comment]
@ultraq 

I have no idea about the interaction between thymeleaf-layout-dialect and thymeleaf-extras-springsecurity4. As you indicated, they don't seem to relate with each other at all. That has been said, I did reproduce this on both CentOS 7 and Windows 7 against STS and IntelliJ. Of course, this could be a misconfiguration on my pom.xml?

Anyway, I managed to solve this by specifying version on thymeleaf-extras-springsecurity4. So, I guess layout-dialect is just accidentally involved into this complication by my biased observation. The following pom.xml section covers the dependencies works for me:

```xml
        <dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-thymeleaf</artifactId>
	</dependency>
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity4</artifactId>
            <version>3.0.2.RELEASE</version>
        </dependency>
	<dependency>
		<groupId>nz.net.ultraq.thymeleaf</groupId>
		<artifactId>thymeleaf-layout-dialect</artifactId>
	</dependency>
        <dependency>
              <groupId>org.codehaus.groovy</groupId>
              <artifactId>groovy-all</artifactId>
              <version>2.4.6</version>
              <scope>compile</scope>
        </dependency>
```  
Well, the last groovy 2.4.6 is necessary for your layout-dialect. It's only needed for compilation?

**Comment by hellocomrade** [comment]
BTW, spring-boot-dependencies-2.0.0.BUILD-SNAPSHOT.pom has groovy.version 2.4.7 as default

**Comment by ultraq** [comment]
Groovy is needed for runtime as the layout dialect is written in Groovy.

> BTW, spring-boot-dependencies-2.0.0.BUILD-SNAPSHOT.pom has groovy.version 2.4.7 as default

I think Spring Boot always had support for Groovy code, but it might be something that devs can opt out of.  Spring Boot has a *lot* of dependencies, I'm not always sure which ones are used.

Anyway, thanks for sticking with this for as long as you have! 👍  The weekend finally happened and I've created that test project, doing pretty much the same things you did to get the layout dialect going:
 - explicitly add it as a dependency as it's no longer part of the Spring Boot Thymeleaf Starter pack
 - configure it as per the docs on http://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html
 - had to turn on logging for Thymeleaf too to make sure it was being picked up by Thymeleaf (`logging.level.org.thymeleaf=DEBUG`)
 - create a template using the layout dialect

I also noticed as you have that one of the newer Spring Boot snapshots sets a newer version of Groovy, 2.4.9 in my case, which once you include the layout dialect it gets updated to use that (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml#L82).

So yeah, looks like if someone chooses to use Spring Boot 2.0, they have to manually add the layout dialect.  I think the fix here is to document that.  I might even give it its own section just like the 1.x -> 2.x migration guide had.

I'll also continue investigating the interaction with the thymeleaf-extras-springsecurity4 dialect in a new issue.

**Comment by ultraq** [comment]
The 2 new issues to come out of this: #153, #154

**Comment by adnanmerrakchi** [comment]
this week i was working with spring boot 2.0.0 (maven), but the whole week i encountered a problem the web pages doesnt recognize layout attribute, after downgrading to 1.5.9 the web page starts working so it seems the spring boot v2.0.0 doesnt support yet all thymeleaf features.

**Comment by ultraq** [comment]
Hi @adnanmerrakchi, Spring Boot 2 doesn't come with the layout dialect by default (you have to explicitly add it as a dependency in your `pom.xml`/`build.gradle` file), so that could be one reason why downgrading to Spring Boot 1 has it suddenly work.  Have you tried adding the layout dialect dependency when using Spring Boot 2?

**Comment by adnanmerrakchi** [comment]
hi bro @ultraq  to be honest no ! i didn't try it but i will do that to see if it will work 👍
