### ISSUE TITLE
data-th-if evaluation does not have precedence in th-block 

### ISSUE THREAD

**Issue by g3ek** [ultraq/thymeleaf-layout-dialect#151]
It used to be that:

`<th-block data-th-if="${expression}" data-layout-insert="expression"/ >`  worked fine to not display the block when needed because data-th-if attribute got evaluated first.

Now though we get NPE's since upgrading to v3.0.3 and thymeleaf layout dialict v2.1.2.

Putting the display block in a conditional block fixes the problem but it's of course not as pretty.

**Comment by ultraq** [comment]
I've just added some tests to show the interaction of the `layout:insert` processor with `th:if` (you can see them here: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/includes/Insert-IfPrecedenceFalse.thtest, https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/includes/Insert-IfPrecedenceTrue.thtest), but both of them seem to be working as expected.

You might have revealed another bug though.

Just like in Thymeleaf 2, the precedence of the `include`/`replace` processors was always higher than `th:if`, and so they ran first.  With `include` (and now `insert`), the `th:if` would then run afterwards, which would remove or include the template fragment.  In the case of `replace`, it always replaced the current element with the fragment, meaning it removed your `th:if` condition.

Your example and getting a `NullPointerException` gives me another idea though: failure to handle `null` for a fragment expression.  As per the [Migration Guide](https://ultraq.github.io/thymeleaf-layout-dialect/MigrationGuide.html), fragment expressions are the new way to select fragments in Thymeleaf templates, and I think a null value there is causing things to fall over.  I've tried replacing those fragment expressions in the tests I've linked above with `null`s, and all sorts of other problems are happening, so I think that might be it.

**Comment by ultraq** [comment]
Hi @g3ek, would you be able to provide a stack trace of the error you get?  I can get problems using the template code you showed above, but they either lead to `TemplateInputException` or `StackOverflowException`, not `NullPointerException` like you so I want to make sure I'm fixing the right thing.

**Comment by ultraq** [comment]
Closing, no response from the OP 😢  Have added the `null`- check to the dependent project and released it as part of 2.2.2, but can't verify if it fixes things.
