### ISSUE TITLE
URI is not registered (Settings | Languages & Frameworks | Schemas and DTDs)

### ISSUE THREAD

**Issue by Ahaochan** [ultraq/thymeleaf-layout-dialect#158]
hello , I use IntelliJ IDEA  to develop thymeleaf。
but the `xmlns:layout` has a warning `URI is not registered (Settings | Languages & Frameworks | Schemas and DTDs)`。
Although it really is useful.
how i fix the warning ? thx.
```html
<!DOCTYPE html>
<html lang="zh-CN" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
      xmlns:th="http://www.thymeleaf.org"
      xmlns:sec="http://www.thymeleaf.org/"
      layout:decorate="~{base/layout_admin}">
</html>
```

**Comment by ultraq** [comment]
You can make this check go away by going to the section identified by the warning message (open your Settings, then go to Languages & Frameworks > Schemas and DTDs) and add an entry in the Ignored Schemas and DTDs section for the URL.

![screen shot 2017-05-12 at 9 23 19 pm](https://cloud.githubusercontent.com/assets/1686920/25991982/5451dfba-3759-11e7-9f1e-687a7b659d9a.png)

**Comment by Programmeurz** [comment]
How to open The android studio "settings"
being a while looking for it but no way

**Comment by ultraq** [comment]
On a Mac, you can get to settings by pressing the `Command` + `,` keys, or the `<Name of program, eg: IntelliJ IDEA>` > `Preferences` menu item.  I'm not so sure where to find this on Windows though.  I would guess under the `File` menu as I can see a lot of other settings-related items in there.

I'm not 100% sure if this applies for Android Studio though - I've not installed the program, but given it's based on the same IDE core that JetBrains uses for its other IDE products, I'd expect settings to be reached in the same way.  Also, Android Studio might not have the same Settings layout as it'll have different plugins installed compared to IntelliJ IDEA.  This stuff looks like it belongs to an XML plugin or XML validation plugin, and given Android apps uses XML files for their manifests and configuration, I hope it'd come installed w/ Android Studio.

**Comment by Dineshnirmania** [comment]
HI Ultraq

I'm also facing same issue but in android app development.

Do you know how to fix this issue in android?

Thanks,
Dinesh Kumar

**Comment by rvbhardwaj** [comment]
[
![capture](https://user-images.githubusercontent.com/40655549/52519424-271b1380-2c81-11e9-88d4-2a18b430e7aa.PNG)
]can you please help me to solve this problem i am new to android studio any one

**Comment by dav1d337** [comment]
i am facing the same problem

**Comment by EichelTony** [comment]
i also do have the same issue like @rvbhardwaj and @dav1d337 

Thx Tony

**Comment by yashadagotmare** [comment]
Did anyone find a solution to this? I am stuck to the same issue. Thankyou.

**Comment by tovidd** [comment]
i do overwrite the .xml file from my backup file, and its worked fined, no errors.

**Comment by umairhY** [comment]
i am also facing same problem

**Comment by katleej** [comment]
Same....

**Comment by ultraq** [comment]
Hey everyone, I installed Android Studio the other day, and I don't think any of the posts since my last response are actually to do with the layout dialect.  Looking at one of your screenshots, that's not the layout dialect at all, but rather the Android layout XML schemas.  As such, you might have more luck over on StackOverflow: https://stackoverflow.com/questions/16883427/why-is-android-studio-reporting-uri-is-not-registered
