### ISSUE TITLE
 Could not parse as assignation sequence on layout parameter pass

### ISSUE THREAD

**Issue by logemann** [ultraq/thymeleaf-layout-dialect#170]
Hi,

i am trying to achieve that:
https://ultraq.github.io/thymeleaf-layout-dialect/Examples.html#passing-data-to-layouts

my layout:
`
<a href="/devportal/main" th:href="@{/main}">
         <strong><span th:with="${loginout}"></span></strong>
</a>
`

my child:

`<html xmlns:th="http://www.thymeleaf.org"
      xmlns:layout="http://www.thymeleaf.org"
      layout:decorate="~{layout.html}" th:with="loginout='Login'">`

but i am getting this exception on parse:

org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as assignation sequence: "${loginout}" (template: "layout.html" - line 144,

Thanks for infos

**Comment by ultraq** [comment]
Hi @logemann, it looks like my docs have a mistake!

Looking at the example at the URL you've given, that `th:with` in the layout file should be `th:text` instead.  Applying that to your code, if you change the `<span th:with="${loginout}">` to `<span th:text="${loginout}">`, you should be able to get your code working.

Sorry about that mistake; I'll fix the docs up very soon.

**Comment by logemann** [comment]
thanks. appreciated this feedback.
