### ISSUE TITLE
LayoutDialect : impossible to import

### ISSUE THREAD

**Issue by BeRoots** [ultraq/thymeleaf-layout-dialect#175]
Hi :)

I have a problem that I can not solve with spring boot 2.0.3 and thymeleaf 3.0.9 (sping 5). On my demo version with spring boot 1.5.14 I use a LayoutDialect for thymeleaf and it work nice. In version 2.0.3 of spring boot I can not use this layout. Here are the git version 1.5 and 2 (https://github.com/BeRoots/spring-boot-1.5.14/tree/fix-localization and https://github.com/BeRoots/spring-boot-2-demo).

As you will see in version 2 I do not have the links defined in the <body> of app-layout.html (before the content section). 

If I add thymeleaf-layout-dialect.2.3.0 as dependency in my pom.xml I have a warning that says "duplicate managed version 2.3.0 for thymeleaf-layout-dialect".

But I can not import it with the namespace nz.net.ultraq.thymeleaf.LayoutDialect without this extra dependency in pom.xml. I haven't test with extra dependency but it's stupid if a version is already include by spring-boot 2.

If someone has an idea ;)

**Comment by zhanhb** [comment]
Thymeleaf Layout Dialect is included in Spring Boot Starter Thymeleaf 1.x, not 2.x

**Comment by BeRoots** [comment]
But why STS (Spring Tools Suite IDE) alert me with a warning that says "Duplicate managed version 2.3.0 for thymeleaf-layout-dialect" in pom.xml on a spring boot 2.0.3 project with Spring Boot Starter 2.0.3 added by the spring initializr?

**Comment by zhanhb** [comment]
The version is managed in the parent spring-boot-dependencies. So you can declare without specifing the version.
```xml
<dependency>
    <groupId>nz.net.ultraq.thymeleaf</groupId>
    <artifactId>thymeleaf-layout-dialect</artifactId>
</dependency>
```

**Comment by BeRoots** [comment]
Ok. Thank you. I thought that managed meant included. I had read that thymeleaf-layout-dialect had been removed. This solves the problem.
