### ISSUE TITLE
There is not method getPrifix in class IDialect

### ISSUE THREAD

**Issue by zhanhb** [ultraq/thymeleaf-layout-dialect#184]
https://github.com/ultraq/thymeleaf-layout-dialect/blob/333ee74ea8d386fb120fe19568feda3aeca07189/source/nz/net/ultraq/thymeleaf/context/extensions/IContextExtensions.groovy#L83
There is not method getPrifix in class `org.thymeleaf.dialect.IDialect`

**Comment by ultraq** [comment]
Hmm, true, there's only one in `IProcessorDialect` https://www.thymeleaf.org/apidocs/thymeleaf/3.0.11.RELEASE/org/thymeleaf/dialect/IProcessorDialect.html  I might have to do an `instanceof` check just before this in case the dialect isn't a processor-based one (eg: an `IExpressionObjectDialect`).

**Comment by ultraq** [comment]
Looks like it's been that way since it was introduced in 2.0.2: https://github.com/ultraq/thymeleaf-layout-dialect/commit/a7db9adb7d9463f9399a846ed08a8548a53939d2#diff-eda292cb178c2121508fb358bf09ffd7R88  I may consider leaving this alone so the code can remain simpler looking and not have to do type checking.

**Comment by ultraq** [comment]
Yeah, I'm not going to be doing anything about this issue.  In Groovy it'll be fine as per my comments above.  As for Java, either casting to `IProcessorDialect` should be OK, or making use of the generic type of the class being searched for (`Class<IProcessorDialect>`) to ensure that results are only of that type should also be enough to ensure type safety, eg:

```java
<T> String getPrefixForDialect(Class<T extends IProcessorDialect> dialectClass) {
  DialectConfiguration dialectConfig = (search for dialect config here)
  return ((T)dialectConfig.getDialect()).getPrefix()
}
```
