### ISSUE TITLE
Possible bug of code

### ISSUE THREAD

**Issue by zhanhb** [ultraq/thymeleaf-layout-dialect#185]
https://github.com/ultraq/thymeleaf-layout-dialect/blob/9e1d3b9b0d1b26840d906444e5d96c3455342fd9/source/nz/net/ultraq/thymeleaf/decorators/strategies/GroupingStrategy.groovy#L71
Where is the definition of the variable positions?

**Comment by ultraq** [comment]
Looks like a copy/paste error on my part.  That's supposed to be `headModel.size()`.

**Comment by ultraq** [comment]
Fixed in `2.4.1-SNAPSHOT`.
