### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by robinarehen** [ultraq/thymeleaf-layout-dialect#188]
1. WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/root/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.6/6936e700f0fb1b50bac0698ada4347a769d40199/groovy-2.5.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int).
WARNING: 
2. WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
W.
3. WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations.
4. WARNING: All illegal access operations will be denied in a future release

**Comment by ultraq** [comment]
Yup, this is coming out of Groovy with issues already being tracked in a few places, eg:
 - https://issues.apache.org/jira/browse/GROOVY-8339
 - https://github.com/apache/groovy/pull/905

I'll upgrade the dependency whenever that gets resolved.

The warnings can be safely ignored for now, or there are some command line flags mentioned in the JIRA above that you can add to remove them from the logs.

**Comment by baturman** [comment]
I believe both issues solved. Can you please upgrade groovy dependencies?

**Comment by laurensk** [comment]
Yes, the issues have been resolved. Please update the dependencies.
