### ISSUE TITLE
Facing issues loading my template propertly

### ISSUE THREAD

**Issue by navindercsb15** [ultraq/thymeleaf-layout-dialect#191]
Hello Sir, I am facing issue loading my thymleaf layouts. The fragments are working properly, but the output page looks like the css or javascripts files has not been loaded properly. I have used syntax  <script th:src="@{/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js}"></script> to load my scripts and for loading my css <link th:href="@{/vendors/bootstrap/dist/css/bootstrap.min.css}" rel="stylesheet">. But I can't understand what is the issue. Please help me out to resolve this issue.

**Comment by ultraq** [comment]
Covered in #190.
