### ISSUE TITLE
how to set the default layout

### ISSUE THREAD

**Issue by yuzd** [ultraq/thymeleaf-layout-dialect#203]
```
<html lang="en" xmlns:th="http://www.thymeleaf.org" layout:decorator="layout/default" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">

<th:block layout:fragment="content">

```````````my child page content```````````````````````

</th:block>
</html>



```
in my child pages , i must do code layout:decorator and set layout:fragment for every page.
i do not want to code that for every child page .
can i  code in server(Controller) side.?

**Comment by dhovart** [comment]
@yuzd why did you close the issue ? Did you find a way to do this ?

**Comment by yuzd** [comment]
No solution was found, but no one answered, so I turned it off
