### ISSUE TITLE
Content assist not showing up in STS 4

### ISSUE THREAD

**Issue by fenzox** [ultraq/thymeleaf-layout-dialect#207]
After installing the software from Eclipse marketplace and adding thymeleaf nature to the project, the content assist is still not showing up. Is there something I'm doing wrong?

**Comment by ultraq** [comment]
I see you've also raised this question against the Eclipse plugin (https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/92#issuecomment-665109903), and I suspect it's more likely to be an Eclipse plugin thing, so I'm closing this issue in favour of your question over there.
