### ISSUE TITLE
Assemble fatjar give problem with dialect

### ISSUE THREAD

**Issue by stripcode** [ultraq/thymeleaf-layout-dialect#220]
Hello.
This happened when I assembled fatjar for micronaut(3.1.0) app for deploy to AWS Beanstalk. I run java -jar fatjar.  If I run my app in Idea(without jar) - everything is ok(dialect works).

![Снимок экрана 2021-10-12 в 23 21 45](https://user-images.githubusercontent.com/20899494/137008897-ad5924e4-438f-4d02-ad82-76c132b3796e.png)
![Снимок экрана 2021-10-12 в 23 23 12](https://user-images.githubusercontent.com/20899494/137009125-b1336fcf-bf29-4a8a-8eb7-2c70a4b1a325.png)
![Снимок экрана 2021-10-12 в 23 25 21](https://user-images.githubusercontent.com/20899494/137009324-170e6318-5e32-4420-9517-f9ac039d3377.png)

**Comment by ultraq** [comment]
Huh, that's an interesting one.  It looks like Micronaut has its own Thymeleaf views and the like: https://micronaut-projects.github.io/micronaut-views/latest/guide/#thymeleaf  This is a new one to me, I'll have to take some time to look into this 🤔

**Comment by stripcode** [comment]
Thanks a lot. I checked that advice. It resolved my problem. Great work!
