### ISSUE TITLE
Support for Groovy v4

### ISSUE THREAD

**Issue by mmoayyed** [ultraq/thymeleaf-layout-dialect#224]
Hello, it appears that this project's support for Groovy is based on the 3.x line, scoped to `org.codehaus.groovy` namespace. Groovy 4 has been released under new coordinates from the ASF. It would be great for `thymeleaf-layout-dialect` to start supporting Groovy 4 as well. I don't anticipate this to be a lot of work, and hopefully should remain mainly cosmetic, changing package names and references like that. 

If you'd like and are open to it, I am happy to submit a pull request and accommodate this change. Thank you!

**Comment by ultraq** [comment]
Hey 👋  I've recently started upgrading and testing a lot of my projects with Groovy 4 since I'm pretty excited about this release, so this will definitely be happening for the layout dialect as well!

**Comment by mmoayyed** [comment]
Great to hear, thank you. Please let me know if I can assist with anything to move this along.

**Comment by ultraq** [comment]
An update: I've got a `groovy4` branch with updated dependencies, and have published a `3.1.0-SNAPSHOT` version from it that I'm trialing in one of my projects and it seems to be working with a quick manual test.  However, this is with using Gradle's module resolution tricks to force the Groovy 4 artifact in place of all of the Groovy 3 ones pulled in by dependencies, so it's not quite proper Groovy 4 support and more like 'hoping everything still compiles and runs' 🤞  Some of these dependencies are my own libraries and I'm working through those now.

The rest are for verification, and the one I'm keeping an eye on is Spock, which I use for testing.  It was looking like their 2.1 release would include Groovy 4 support, but 2.1 has just come out without it.  I'm currently using a snapshot version of theirs to relax their Groovy version restriction.

There's also Codenarc for static analysis, but that one has always been a bit annoying to keep updated, so I'm kind of resigned to having to do something to make that work anyway.

So nothing is obviously broken, but I'm waiting on a few more things to fall into place as I'd rather not build things atop too many prerelease dependencies or have to keep little hacks around in the build config in a shipping version.

**Comment by mmoayyed** [comment]
Thanks very much for the update.  I will also consider switching [CAS](https://github.com/apereo/cas) to use `3.1.0-SNAPSHOT` and will report back results. Barring weird issues, would you say 3.1.0 would be ready for a release some time in the next couple of months?

**Comment by mmoayyed** [comment]
Happy Friday! I have been testing the latest snapshot and I have not found an issue so far. Thank you very much for working on this. Do you think this might be ready for a release? Maybe an RC?

**Comment by ultraq** [comment]
Hey there, I've been using the snapshot without issues in other projects too, so yeah I'm pretty happy to release this.

I'm putting together the 3.1.0 release together now, maybe it'll even be up on Maven central by the time you read this 🙂
