### ISSUE TITLE
Hello, do you support Thymeleaf v3?

### ISSUE THREAD

**Issue by oomgomgxx** [ultraq/thymeleaf-layout-dialect#234]
Hello, do you support Thymeleaf v3?

**Comment by zhanhb** [comment]
thymeleaf-layout-dialect with version greater or equal to 2.0.0 supports thymeleaf 3.0.
The current version is not tested on thymeleaf 3.1.

**Comment by ultraq** [comment]
And although the layout dialect isn't built/tested against Thymeleaf 3.1, I've found that the current version does work with Thymeleaf 3.1 in other projects I've used it in.
