### ISSUE TITLE
Passing variables to decorator

### ISSUE THREAD

**Issue by igo** [ultraq/thymeleaf-layout-dialect#32]
Please allow passing variables to parent decorator with `th:with` like this: 

``` xml
<body layout:decorator="templates/main-page" th:with="hello='world'">
    <div layout:fragment="content>...</div>
</body>
```

**Comment by kalgon** [comment]
Is it possible to declare the variables in the decorator and giving them default values?

*layout*

    <html layout:attributes="hello = 'Hello World!', showMenu = true">

*page*

    <html layout:decorator="layout (showMenu = false)">

or

    <html layout:decorator="layout" th:with="showMenu = false">

**Comment by ultraq** [comment]
Been a while since I tried to see how merged attribute behaviour would work, but you should be able to declare values in the decorator with plain old `th:with`, then set them again in your pages.  The one with the nearest scope should win out.

**Comment by kalgon** [comment]
I tried that and the value declared in the decorator always wins. If I don't declare it, the one in the decorated page is used. So it's not possible to have default values in the decorator. Another problem I have with not being able to declare them in the decorator is that you have to search for them in the HTML code before you can use them. If they were declared at the top of the decorator, it would be easier to know what variables can be used.
