### ISSUE TITLE
Support specifying decorated fragments inside layout template

### ISSUE THREAD

**Issue by stevensheehy** [ultraq/thymeleaf-layout-dialect#49]
One of the nice features of tiles 2 is that you can apply a layout to one or more decorated views inside a centralized location, the tiles-defs.xml. This allows the user to avoid from having to edit each decorated fragment in order to explicitly define which decorator it should use. As a result, the decorator and the decorated become decoupled and one can easily swap out the layout used without editing hundreds of files.

For thymeleaf-layout-dialect, a completely centralized definition would be overkill, but it would be really nice to be able to define which fragments a particular layout should decorate within the actual layout using some sort of wildcarding (see [Tiles Wildcards](https://tiles.apache.org/framework/tutorial/advanced/wildcard.html)). I don't know exactly how this could be done, but one option would be to use a tiles like wildcard inside the layout:fragment attribute in the layout. Possible example using the readme example:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
  <body>
    <header>
      <h1>My website</h1>
    </header>
    <section layout:fragment="content_folder/* :: content">
      <p>Page content goes here</p>
    </section>
    <footer>
      <p>My footer</p>
    </footer>  
  </body>
</html>
```
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <body>
    <section th:fragment="content">
      <p>This is a paragraph from content page 1</p>
    </section>
  </body>
</html>
```
Hopefully, the xmlns:layout might not even be necessary to use in the decorated views. Instead the regular th:fragment might be sufficient.

**Comment by ultraq** [comment]
Hmm, I don't see myself doing anything about this issue, some 2 years after it was first raised, mostly because I can't figure out a way of overcoming the problem I identified in the last paragraph of my previous reply.

So I'm going to close this as 'not doing', sorry.
