### ISSUE TITLE
More control for head tag

### ISSUE THREAD

**Issue by demwis** [ultraq/thymeleaf-layout-dialect#61]
Hello. Do you plan to add more control for the head tag? I mean, that it will be nice to have some marker-placeholder in a decorator, so that a decorated page head content can be placed in exact place of it's decorator. Now as I see, a decorated page's content is placed only to the end of merged head tag. 
Now I have faced the issue with applying google analytics scripts, which should be placed exactly before the closing head tag.

**Comment by ultraq** [comment]
Done, I hope!  See #59.
