### ISSUE TITLE
Initial loads after rebuild render incorrectly

### ISSUE THREAD

**Issue by ronnyek** [ultraq/thymeleaf-layout-dialect#62]
For first few attempts to render a page that utlizies layout dialect after a rebuild... It looks like it just renders the layout and the content together as a whole. After a while, it starts kicking out pages rendering as it should.

Is this a sign that I am doing something wrong? Or did I just catch it before the layout dialect engine started rendering appropriately?

-- update
Seems like after rebuild, it takes 4-5 refreshes of the page for the content to be rendered appropriately. I tried ot make sure the layout dialect was registered as soon as I could in the process, but doesnt seem to matter. Is there any logging or anything I can turn on to help diagnose why it seems like spring ignores layout dialect stuff for many page loads

**Comment by ultraq** [comment]
So I can't figure out what might be happening here.  I think Thymeleaf instantiates everything just once per template engine instance when you first access a page, and then after that everything is either fresh copies of a template, or from a cache that Thymeleaf keeps to itself.  With Spring in the mix, I'm not entirely sure how that works, so can't help much there sorry :/

And there's not much logging in the layout dialect to turn on.  You could configure `org.thymeleaf` loggers to spit out more stuff, but I don't have a lot of logging here.  You could maybe download the source files so you can at least debug the decorator code to see if what's happening falls in line with what you expect.

Do you happen to have some templates or a small web project where this happens to you so I could try reproduce the issue?
