### ISSUE TITLE
Question: Is there a way to reference a layout in the classpath? 

### ISSUE THREAD

**Issue by datpham23** [ultraq/thymeleaf-layout-dialect#65]
Is it possible to use a layout from another jar via the classpath?

     <html layout:decorator="classpath:SomeLayout">

**Comment by ultraq** [comment]
It *should* be possible to load files via the classpath as I use the same lookup mechanism as other things in Thymeleaf, like `th:include`/`th:replace`.  To make it work, you should have a `ClassLoaderTemplateResolver` as one of your configured template resolvers.  Most of the examples given only show configuring 1 template resolver, usually a `ServletContextTemplateResolver` as that's most relevant to web projects, but you can add multiple template resolvers to the template engine.

**Comment by datpham23** [comment]
Thats awesome.
So would this be the right syntax to load something from the classpath?
     <html layout:decorator="classpath:SomeLayout">

**Comment by ultraq** [comment]
The syntax is the same as in all the Thymeleaf examples, so `<html layout:decorator="SomeLayout">` will still work for a layout called `SomeLayout`.  The difference is in the `ClassLoaderTemplateResolver` and how you set that up, eg: in a Spring config file

```xml
<bean id="templateResolver" class="org.thymeleaf.templateresolver.ClassLoaderTemplateResolver">
  <property name="prefix" value="org.example.layouts."/>
  <property name="suffix" value=".html"/>
  <property name="templateMode" value="HTML5"/>
  <property name="cacheable" value="true"/>
</bean>
```

So the above template resolver, plus what's in `decorator:layout` will load a file, called SomeLayout.html inside the org.example.layouts classpath.

**Comment by datpham23** [comment]
Cool, thanks for the help!
