### ISSUE TITLE
Head merge drops conditional comments.

### ISSUE THREAD

**Issue by stoye** [ultraq/thymeleaf-layout-dialect#70]
We have a responsive_layount.html template that acts as our base template for everything. We have several templates that get merged into this one that have conditional comments for things like respond.js and other IE8 fixes. When we include these in the responsive_layout file, everything's fine, but if we include them in the other templates (that get merged with responsive_layout), they get blown out, and never get served.

**Comment by ultraq** [comment]
Hi there @stoye, I've created a [test case](https://github.com/ultraq/thymeleaf-layout-dialect/blob/dev-thymeleaf-2.1/Tests/nz/net/ultraq/thymeleaf/tests/decorator/Decorator-HeadConditionalComments.thtest) and fix for the issue you described, and uploaded a 1.2.9-SNAPSHOT version of the layout dialect to Maven with this fix.  Could you give that version a try, see if it works for you?

**Comment by stoye** [comment]
Hey there,

Sorry for the crazy late reply. This fell off our radar for a while. It seems to work marvelously (and thanks for keeping the SNAPSHOT up). I'll keep an eye out for when this gets released as a bugfix, I really appreciate it.

**Comment by stoye** [comment]
So it turns out this is a pretty big blocker for us. Any opportunity for this getting rolled into a release rather quickly would be greatly appreciated!!

**Comment by ultraq** [comment]
Happy to make a 1.2.9 release with just this fix in it when I get home tonight (dunno which timezone you're in, but for me that'll be about 12 hours from the posting of this message.  I'll see if I can't kick that off earlier given Maven's delay on releasing new uploads).

**Comment by ultraq** [comment]
And the 1.2.9 release is now live.  The Maven version is now making its way through the automated release process, but should show up in the next few hours.

**Comment by stoye** [comment]
Awesome, thanks so much! Working perfectly.
