### ISSUE TITLE
Groovy dependency?

### ISSUE THREAD

**Issue by chrylis** [ultraq/thymeleaf-layout-dialect#74]
Does TLD have a hard or optional dependency on Groovy? I updated from 1.2.7 to 1.3.0-SNAPSHOT, and now I'm getting a transitive dependency that's pulling in the wrong Groovy package (2.3.11 instead of 2.4.3-indy). If it's not a hard dependency, it'd be helpful to make it `provided`.

**Comment by ultraq** [comment]
1.3 is rewritten in Groovy, so it is needed.  As for which version, I'm not really sure - I just included the latest of the 2.4 releases, but can probably go down a few minor versions depending on what features I'm really using.

Also, are you sure it's trying to pull in the indy version of the JAR?  I didn't compile it against the `invokedynamic` version of Groovy, nor did I use any of the `invokedynamic` compile flags

**Comment by chrylis** [comment]
*I* am trying to include indy. The problem is that Maven's classifier system doesn't recognize them as equivalent and tries to include the legacy version alongside it. The latest 1.3.0-SNAPSHOT was pulling in 2.3.11 as a hard dependency.

**Comment by ultraq** [comment]
OK.  I'm kinda torn on resolving this one: on the one hand, if devs don't explicitly include Groovy themselves, then the layout dialect isn't going to run at all; on the other hand, it makes it annoying for those including the indy versions of Groovy, like yourself.

The non-indy JAR is the default in the Groovy download distribution and for command-line building, so one has to go out of their way to include the indy version of Groovy.  If someone chooses to do that, then I'd assume that they know what they're doing for other things like Maven/Gradle configuration and know that they can add an exclusion rule to prevent the layout dialect pulling down the standard Groovy JAR in favour of the indy one.

**Comment by chrylis** [comment]
I understand where you're coming from, and it's probably the best approach, even though it's a bit irritating in my case. (Maven really just needs global exclusions; I'm having to exclude Groovy from about seven dependencies.) I would highly recommend mentioning the switch to Groovy prominently in the docs.
