### ISSUE TITLE
Make use of the result of the title after going through the decoration process

### ISSUE THREAD

**Issue by ultraq** [ultraq/thymeleaf-layout-dialect#76]
As mentioned in @chrylis' latest comments on issues #64 and #72, he'd like to make use of the result of the content of the `<title>` element, after decoration, in other parts of the page.

2 possible solutions have come to mind:
1. Modify the `layout:include` processor to see if we're picking out a `<title>` element and go find the resulting title instead of the usual inclusion mechanism (proposed in the linked issues)
2. Put the resulting title as a variable on the template processing context so it can be accessed by any standard Thymeleaf processor.

I'm leaning towards the second solution because:
 - then I don't have to change the current behaviour of `layout:include`, which mostly mimics Thymeleaf's `th:include` (introducing this behaviour would make it inconsistent with Thymeleaf, and a surprise to developers expecting a similarly-named processor to act similarly)
 - also, implementing the first solution would have the code for title stuff be further tangled in classes that don't have anything to do with titles, and I just don't like that (it's already a bit like that even after the latest refactor).

Possible look for the second solution:

```html
<html layout:decorator="layout.html">
  <head>
    <title>My page</title>
  </head>
</html>

<html>
  <head>
    <title layout:title-pattern="$CONTENT_TITLE - $DECORATOR_TITLE">My website</title>
  </head>
  <body>
    <h2 th:text="${layout.resultingTitle}">"My page - My website" will end-up in here</h2>
  </body>
</html>
```

The special `layout` object/map would hold the title information, and takes the onus of this special use case out of this dialect and its processors.

It also paves the way for me deprecating/removing the `title-pattern` processor (#75), which is something that's been on my mind a lot as of late.

**Comment by ultraq** [comment]
I may **have** to implement the first solution if I want to do something in a timely manner - the second solution (if it is to pave the way for me dropping the `title-pattern` processor) still has some unanswered questions.

**Comment by chrylis** [comment]
I have no idea what's involved in making any of this work, so I don't think I have standing to critique whatever solution(s) you come up with.

**Comment by ultraq** [comment]
Second solution implemented, and accessing the resulting title in the template will be just like that: `layout.resultingTitle`.
