### ISSUE TITLE
IntelliJ can't autocomplete with xmlns

### ISSUE THREAD

**Issue by skollro** [ultraq/thymeleaf-layout-dialect#78]
Hi,
I've got  a question: Why are IntelliJ's autocomplete features for XML not usable with xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" in the html tag? It says "The external resource can't be fetched"

**Comment by mknabe** [comment]
+1 The link is throwing a 404

**Comment by skollro** [comment]
I hope this is fixed soon... Has anyone this definition file locally for me?

**Comment by ultraq** [comment]
IntelliJ's autocompletes are only for the standard Thymeleaf dialect, and so there is built-in code to specially handle the Thymeleaf namespace and processors.  There is no such handling for Thymeleaf extensions, like this one.
