### ISSUE TITLE
Adjust ReadMe to address default suffix in example.

### ISSUE THREAD

**Issue by Sector7B** [ultraq/thymeleaf-layout-dialect#83]
In the readme example you have Layout.html, but reading this: https://stackoverflow.com/questions/27214584/how-to-add-the-layout-dialect-to-spring-boot-thymeleaf-autoconfiguration-file
I had the same problem as this gentleman did.  A note of this issue or adjusting the example might save some people a lot of time.
Good job.

Thanks.

**Comment by ultraq** [comment]
Cool cool, thanks for letting me know about that (I didn't know Spring Boot defaults to a `.html` suffix - and given Spring is a major use case for this dialect, then it's some useful info!)  I'll decide on what to do about that one in a bit.

**Comment by ultraq** [comment]
Readme updated for 1.3.2 onwards.
