### ISSUE TITLE
how call in modal 

### ISSUE THREAD

**Issue by joe-diego** [ultraq/thymeleaf-layout-dialect#84]
how pass paramers in bootstrap modal ??

====================================MY table==================================

![image](https://cloud.githubusercontent.com/assets/5587972/10058002/7a9fd850-6219-11e5-9521-83a3d4e65ff0.png)

working normally.

more if I try to spend some modal parameter in not working.
==================================my view===================================

![thymeleafissues](https://cloud.githubusercontent.com/assets/5587972/10058323/37c5a4cc-621b-11e5-82c3-7faf2451661f.png)

============================My template modal ============================
![image](https://cloud.githubusercontent.com/assets/5587972/10057907/fb942c0a-6218-11e5-8225-9a4974c74b0a.png)

==================================result=====================================

![image](https://cloud.githubusercontent.com/assets/5587972/10058153/56674ddc-621a-11e5-8aaa-dba096e57f10.png)

How can I solve?
How can I call the modal concatenating String with my img.codigo?
in the table thymeleaf is right ...
a long time since I can not solve
Att.

========================================================================

**Comment by joe-diego** [comment]
my dependencies 

 compile "org.thymeleaf:thymeleaf-spring4:2.1.2.RELEASE"
   compile group: 'nz.net.ultraq.thymeleaf', name: 'thymeleaf-layout-dialect', version: '1.2.9'
compile 'org.thymeleaf.extras:thymeleaf-extras-springsecurity4:2.1.2.RELEASE'

**Comment by joe-diego** [comment]
Sorry i am new github..

**Comment by ultraq** [comment]
Hi there, I think Thymeleaf is having trouble processing the parameters you're giving your modal, which is this part:

![screen shot 2015-09-27 at 10 37 37 pm](https://cloud.githubusercontent.com/assets/1686920/10122101/6b06dc98-6568-11e5-95ea-d7ffa99ef644.png)

I think the `modalId` parameter isn't a proper string - the `del_image_+'${img.codigo}'` might need to be `'del_image_'+${img.codigo}` or `|del_image_${img.codigo}|` (the characters at the start and end of that string are pipes as per Thymeleaf's [literal substitutions](http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#literal-substitutions) feature).  Can you try if those work?

**Comment by joe-diego** [comment]
thanks for answering, I removed the modal and made the other way, now I have trouble making validations., there is a project ready to spring mvc and thymeleaf with hibernate and Ben validations so I can take a look and see how to do?
Once again thank you for answering.

**Comment by ultraq** [comment]
There are a few Thymeleaf example projects (https://github.com/thymeleaf?utf8=%E2%9C%93&query=example), but none of them use bean validations.  However, I did find one thorough tutorial on the Spring website (http://spring.io/guides/gs/validating-form-input/) and another one from a blog post (http://blog.codeleak.pl/2014/06/better-error-messages-with-bean.html) so I hope hope those all combined can lead you in the right direction.

**Comment by joe-diego** [comment]
validation doing correctly in the controller, but does not print the view and the data do not come back as they were, for hours on stackoverflow I'm looking for a solution, not more acho..O example above seems to work for me.
