### ISSUE TITLE
Java 6 support does not work with latest version

### ISSUE THREAD

**Issue by rubyripperdev** [ultraq/thymeleaf-layout-dialect#85]
The site mentions it works with Java6, but it is compiled agains java version 1.7. Either update your documentation, or revert the gradle setting to 1.6 please.

**Comment by rubyripperdev** [comment]
Version 1.2.8 still works by the way.

**Comment by ultraq** [comment]
Gah, my mistake.  I still aim to support Java 6 with the 1.x versions - the 1.7 flag in my build is incorrect.  Thanks for letting me know :+1:

**Comment by ultraq** [comment]
I've uploaded a 1.3.1-SNAPSHOT version of the layout dialect with Java 6 support back in it.  Could you give that a try?  Travis CI says it's passing against OpenJDK6.

**Comment by rubyripperdev** [comment]
I could not find the mentioned download, but after a little trial and error I got the gradle build working from the dev branch. After recompiling against the new library, I got the following runtime error:

2015-09-28 10:06:45,149 WARN  org.springframework.web.context.support.AnnotationConfigWebApplicationContext  - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'viewResolver' defined in nl.snsreaal.idm.servlet.beheerschermen.config.SpringConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.thymeleaf.spring4.view.ThymeleafViewResolver]: Factory method 'viewResolver' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateEngine' defined in nl.snsreaal.idm.servlet.beheerschermen.config.SpringConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.thymeleaf.spring4.SpringTemplateEngine]: Factory method 'templateEngine' threw exception; nested exception is java.lang.NoSuchMethodError: groovy.lang.MetaClassImpl.createStaticSite(Lorg/codehaus/groovy/runtime/callsite/CallSite;[Ljava/lang/Object;)Lorg/codehaus/groovy/runtime/callsite/CallSite;
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)

**Comment by ultraq** [comment]
Ah, snapshot releases are on the Maven central snapshots server (you have to configure your Maven/Gradle to use it), but I can give you a link to the JAR here: https://oss.sonatype.org/content/repositories/snapshots/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/1.3.1-SNAPSHOT/thymeleaf-layout-dialect-1.3.1-20150927.092153-1.jar

**Comment by rubyripperdev** [comment]
I keep getting java.lang.NoClassDefFoundError: Could not initialize class nz.net.ultraq.thymeleaf.LayoutDialect. Which is very strange since I do the same configuration in a unit test which passes just fine.

This also happens for the 1.3.0 version with the flag updated to 1.6. Might be some groovy related thing perhaps.

I am happy with the 1.2.8 version though and keep using that one.
