### ISSUE TITLE
xmlns points to non existent page

### ISSUE THREAD

**Issue by ctrl-f5** [ultraq/thymeleaf-layout-dialect#89]
http://www.ultraq.net.nz/thymeleaf/layout gives a 404, and the IDE doesn't understand the dialect attributes...

**Comment by ultraq** [comment]
Hmm, guess the redirect isn't working then - it should be redirecting to this GitHub project.  Will fix.

**Comment by ultraq** [comment]
Redirects fixed to point to their respective GitHub projects.

As for the IDE, if you're using Eclipse you can install the [Thymeleaf Extras Eclipse Plugin] to give you some content assist for the layout dialect and `layout:` namespace.  If you're on other IDEs though, it'll be up to the IDE devs to implement such support.

**Comment by ctrl-f5** [comment]
isn't the whole point of such a namespace URL to point to a file detailing the spec?

**Comment by ultraq** [comment]
I think you're thinking of the second part of an XML namespace declaration which is an optional URL to a schema definition file, eg: `xmlns:blah="http://blah.org/ http://blah.org/definition.xsd"`

Unfortunately, there is no schema definition for Thymeleaf dialects, and the issue for creating one (and thus building it into the parsing system) was dropped: https://github.com/thymeleaf/thymeleaf/issues/9
