### ISSUE TITLE
data attribute style example?

### ISSUE THREAD

**Issue by end-user** [ultraq/thymeleaf-layout-dialect#91]
Could you provide an example of how to use the "data attribute" syntax?

**Comment by ultraq** [comment]
Well, it's just like how you'd use data attributes in Thymeleaf: http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#support-for-html5-friendly-attribute-and-element-names

So, if we take the Content1.html example from the readme (https://github.com/ultraq/thymeleaf-layout-dialect#decorators-and-fragments) and convert the `layout:*` processors into their data attribute equivalents, you'll end-up with something like this:

```html
<!DOCTYPE html>
<html data-layout-decorator="Layout.html">
  <head>
    <title>Content page 1</title>
    <script src="content-script.js"></script>
  </head>
  <body>
    <section data-layout-fragment="content">
      <p>This is a paragraph from content page 1</p>
    </section>
    <footer>
      <p data-layout-fragment="custom-footer">This is some footer content from content page 1</p>
    </footer>
  </body>
</html>
```
