### ISSUE TITLE
Content1.html sample does not work

### ISSUE THREAD

**Issue by lpalomerol** [ultraq/thymeleaf-layout-dialect#94]
Hello.

You are doing an amazing job here! Only one appointment. In your first sample you are including as decorator "Layout.html", and this sample is broken. I've been debugging my Spring project with Maven and I saw the decorator should be only the layout path without html suffix.

```
Content1.html

<!DOCTYPE html>
<html xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
  layout:decorator="Layout.html"> <!-- This should be "Layout" or "address/to/layout" -->
  <head>
    <title>Content page 1</title>
    <script src="content-script.js"></script>
  </head>
  <body>
    <section layout:fragment="content">
      <p>This is a paragraph from content page 1</p>
    </section>
    <footer>
      <p layout:fragment="custom-footer">This is some footer content from content page 1</p>
    </footer>
  </body>
</html>
```

Regards,
L

**Comment by ultraq** [comment]
Thanks for bringing this up - I've got a similar issue about the documentation (#83) in that a lot of popular frameworks that use Thymeleaf and this dialect have a default suffix of `.html` in their configuration files, thus making the `.html` in these examples, redundant.

I'll remedy it all for the next version.

**Comment by ultraq** [comment]
Readme updated for 1.3.2 onwards.
