### ISSUE TITLE
Rename layout:decorator to layout:decorate

### ISSUE THREAD

**Issue by ultraq** [ultraq/thymeleaf-layout-dialect#95]
If we're following the decorator pattern, then what is specified in the `layout:decorator` attribute is the template to be decorated, not the templating doing the decorating.

So would it make more sense to rename the processor to `layout:decorate`?

**Comment by ultraq** [comment]
I'm thinking yes as then each of the processor names are verbs describing what is happening to the target: `decorate` this, `include` that, `replace` a template, etc.

`title-pattern` and `fragment` are still exceptions though :stuck_out_tongue:

**Comment by ultraq** [comment]
So I've incorrectly repurposed the word "decorator" throughout the layout dialect, most problematically in the `title-pattern` processor as one of the replacement tokens, `$DECORATOR_TITLE`.  The value that token represents is the parent/layout page, so that also needs to be renamed appropriately as `$LAYOUT_TITLE`, with the old value as a deprecated fallback to remove in future versions.

**Comment by ultraq** [comment]
Done.  Also added an alias processor that just logs a deprecation warning to maintain backwards compatibility with migrating templates.  Same done for the title pattern token, with a warning emitted when `$DECORATOR_TITLE` is used.  Both logs direct developers to the updated decorator/token, with a link to this GitHub issue too.

**Comment by ItaloOre** [comment]
layout:title-pattern="$CONTENT_TITLE - $DECORATOR_TITLE"
