### ISSUE TITLE
support  dynamite decorator layout in runtime?

### ISSUE THREAD

**Issue by tsengyi** [ultraq/thymeleaf-layout-dialect#97]
e.g. Now we need hardcode the decorator in page user.html. 
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.w3.org/1999/xhtml"
      xmlns:layout="http://www.w3.org/1999/xhtml" layout:decorator="layout/public">

Now I have 2 layout, public.html and admin.html, 
when open  /admin/blog, then use admin.html layout,
and open /pulbic/blog, then user public.html layout.

Does it support ?

**Comment by ultraq** [comment]
You can use a feature of Thymeleaf called Preprocessing Expressions (http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#preprocessing) that can let you write an expression inside the `layout:decorator="..."` part which you can use to switch between different layouts.  For example:

```html
<html layout:decorator="__${isAdmin ? 'admin.html' : 'public.html'}__">
```

The result will then be fed into the `layout:decorator` processor.

**Comment by tsengyi** [comment]
It's work, thx
