### ISSUE TITLE
Possible migration to  java instead of groovy?

### ISSUE THREAD

**Issue by ieugen** [ultraq/thymeleaf-layout-dialect#98]
Hello,

First of all I'm using yor plugin in a few project and I'm pretty happy with it. Thank you for all the hard work you've put in. 

One thhing that bothers me is that it depends on groovy which brings a big dependency of 4.3MB. If this was the only dependency in a project it shouldn't be a big issue, but dependencies tend to add up. I've checked my projects and groovy seems to be the bigges one.    

I know languages are a personal choice and I respect that, please don't get me wrong. I also use groovy from time to time and I believe it has it's uses, especially in devops environments and with gradle. 

I do feel however that in this case it's benefits are not really felt from deployment/ distribution perspective. 

My question is: would you be open to migrate to Java? It should be doable with two-three day work ? I'm probably be able to put some effor in it if you are committed to this. 

Especially since there is the migration to thymeleaf 3 comming up, it seemms like a good moment. 
I belive this feature will not impact a lot of users since most of them will just use it and not extend it.

Regards,

**Comment by ultraq** [comment]
Hi @ieugen, the short answer is no, I'm not going to write the next version of the layout dialect in Java.

The long answer is that, for various reasons (my day job is JavaScript, so I like being able to bring dynamic types and functional programming into my personal projects; thus I am now unmotivated to write Java code), I actually moved this project from Java to Groovy about a year ago, and don't want to go back to writing it in Java.

The Java -> Groovy migration happened between versions 1.2.9 and 1.3.0, so if you're keen to create your own Java-only fork, then that should be entirely possible and you're absolutely welcome to do so.  Maybe you can use the state of the code as at 1.2.9 as a starting point, or just rename everything in the current state from `.groovy` to `.java` and go from there.  The code is open source and licensed under Apache 2.0, so you've got a lot of freedom there :smiley:

**Comment by ieugen** [comment]
Hi @ultraq, thank you for answering. I respect your reasons. I'll probably for it if I have some time. Thank you for the tip regarding the move from Java ot Groovy.

**Comment by jefffischer** [comment]
I know this thread is closed, but I thought I would mention our results for what it's worth. All else equal in our project using Thymeleaf 3, we see a 30% performance increase loading a test page using the fork of the ultraq dialect at https://github.com/zhanhb/thymeleaf-layout-dialect. Removing the dialect altogether, we see a 44% performance increase for the same test.

JMeter results attached for your reference.

[dialect_results.zip](https://github.com/ultraq/thymeleaf-layout-dialect/files/477824/dialect_results.zip)

**Comment by ultraq** [comment]
Yeah, @zhanhb has been pretty on to it, and if you're looking for a Java-only fork then that is the one I would recommend 👍
