### ISSUE TITLE
Inherit objects from parent layout when using layout decoration

### ISSUE THREAD

**Issue by Kerruba** [ultraq/thymeleaf-layout-dialect#99]
Hi, 

I think would be nice to use variable inheritance within layout template, defining default variables in the base template that can be overridden in the decorating child template.
For example, I've a base template base.html which contains various layout fragments, one of which is the navigation bar. 
I would like to use a currentPage variable to set the active page in the navigation bar using a .active class on the element.
Right now I need to set th:with="currentPage='pageName'" on each child page to correctly setup the navigation, but it would be really useful to have a default value in the base.html template that is inherited in the child template and possibly overwritten by a more specific value.

There's an example that is even clearer (from my point of view):
In my site I've a series of pages dedicated to Help. 
In these pages I've two navigations: the primary one and a secondary one that let you move around the help pages.
I have setup two variables to define which is the current page globally on my site and which is the current page locally in my help pages.
If I want to go to the help home page, for example, here the variables I'm setting up:

```
th:with="currentPage='help', helpPage='home'"
```

If I want instead to go to a contact us page, here the corresponding variables

```
th:with="currentPage='help', helpPage='contactUs'"
```
I have to repeat the currentPage variable for all the help pages, even if it's the same. This is not particularly DRY. Maybe would be better to define a default currentPage='help' inside of the base layout (or a specific layout for all the help pages) and override it just if necessary.
Something like

```html
<!-- __parent_help.html -->
<html th:with="currentPage='help'">
<!-- parent content -->
</html>

<!-- ** BELOW THE DECORATING PAGE -->

<!-- help_contactus layout:decorator="__parent_help.html"-->
<!-- No need to define currentPage because inherited form parent layout -->
<html th:with="helpPage='contactus' >
<!-- specific content -->
</html>
```

What do you think about that?

**Comment by Kerruba** [comment]
So I just found out that if you don't define any other variable in the child template, the child template is actually picking up the default value inside of parent... I'm missing something probably -_-'

**Comment by ultraq** [comment]
Oh hey, you're the one I tried answering in the forums :smile:  Well I guess the merging resulting in `th:with="something=${parentObject},something=${childObject}"` didn't work if you're here.

As you've found, objects defined in the parent/layout template can be seen by the child templates, but there's probably not a way of getting child templates to override those objects because of the way I merge `th:with` attributes.  I think if I changed it to recognize same-named `th:with` variables and have the child one take place of the parent one, will that help for what you're trying to do?

**Comment by Kerruba** [comment]
Hey, thank you for the reply. Well, I think it would be really great to merge all the object as you said. I imagine that all the objects created in all the pages (parent, child and fragments) are collected in a single set of variable, generated from the most generic to the most specific element (ideally parent -> child -> fragment) and while your are composing the template with more specific elements you override variables already available in the set. I'm not sure I explained myself. Do you think is something easy to do?

**Comment by ultraq** [comment]
It should be a matter of updating that merging, so hopefully an easy thing.  (The layout dialect just outputs a new `th:with` processor on the element that the merging takes place, instead of using Thymeleaf's internals to do it, so the results are rather predictable.)  I'll let you know when I make a snapshot version with that in it for you to try.

**Comment by ultraq** [comment]
I've just uploaded a `1.4.0-SNAPSHOT` version of the layout dialect with a change to do much smarter merging of `th:with` variables to support this use case.  Doesn't seem to break existing tests, so that's a plus :grin:  Could you give it a go and let me know if it helps you out?

**Comment by Kerruba** [comment]
@ultraq I'll give it a try and let you know :-) Thank you very much

**Comment by Kerruba** [comment]
Confirmed, 1.4.0-SNAPSHOT is not available as maven dependency, our development build plan just crashed :cry:

**Comment by ultraq** [comment]
Good to see you resolved the snapshot issue.  How's the testing of the fix going?

**Comment by Kerruba** [comment]
I've tested it in a couple of situations, both were totally fine. Maybe I can test it further creating some "crazy" combination of fragments/inheritance, let's see what it will happen :+1:

**Comment by ultraq** [comment]
Cool cool, just eager to release a 1.4.0 version with this change in it once you let me know it's all good 😃

**Comment by Kerruba** [comment]
I think that is alright for what was my need :+1: you can push the new version. In case something is wrong, we can rise a new issue, what you think about it? 😃

**Comment by ultraq** [comment]
Sounds good to me 👍

**Comment by ultraq** [comment]
Version 1.4.0 released.  It should show up on Maven central shortly (although probably not on the search results for a few hours).
